insert into colores(cod, descripcion) values (211,'CIENA');
insert into colores(cod, descripcion) values (219,'AZUL SEÑAL');
insert into colores(cod, descripcion) values (220,'ROJO SEÑAL');
insert into colores(cod, descripcion) values (221,'GRIS MAMPARO');
insert into colores(cod, descripcion) values (222,'GRIS CASCO');
insert into colores(cod, descripcion) values (223,'GRIS CUBIERTA');
insert into colores(cod, descripcion) values (238,'GRIS GRAFITO');
insert into colores(cod, descripcion) values (262,'GRIS A RAYAS');
insert into colores(cod, descripcion) values (264,'ESTAMPADO');
insert into colores(cod, descripcion) values (271,'ROSA');
insert into colores(cod, descripcion) values (272,'59');
insert into colores(cod, descripcion) values (274,'VERDE LABRADOR');
insert into colores(cod, descripcion) values (284,'WENGUE');
insert into colores(cod, descripcion) values (287,'VIROLA');
insert into colores(cod, descripcion) values (288,'NIQUEL');
insert into colores(cod, descripcion) values (293,'GRIS PLOMO');
insert into colores(cod, descripcion) values (295,'PERLADO');
insert into colores(cod, descripcion) values (300,'B1');
insert into colores(cod, descripcion) values (303,'AMARILLO LIMON');
insert into colores(cod, descripcion) values (304,'AZUL PRUSIA');
insert into colores(cod, descripcion) values (305,'AZUL ULTRAMAR');
insert into colores(cod, descripcion) values (307,'AMARILLO VIVO');
insert into colores(cod, descripcion) values (308,'NOGAL ANTIGUO');
insert into colores(cod, descripcion) values (309,'NOGAL RUBIO');
insert into colores(cod, descripcion) values (323,'CHAMPAGNE');
insert into colores(cod, descripcion) values (326,'VISON');
insert into colores(cod, descripcion) values (327,'ESMERALDA');
insert into colores(cod, descripcion) values (328,'MAGENTA/CYAN');
insert into colores(cod, descripcion) values (329,'GRIS/NEGRO FOTOGRAFICO');
insert into colores(cod, descripcion) values (330,'NEGRO MATE/AMARILLO');
insert into colores(cod, descripcion) values (331,'GRIS MARMOLADO');
insert into colores(cod, descripcion) values (332,'VERDE MATE');
insert into colores(cod, descripcion) values (334,'GRIS ESPACIAL');
insert into colores(cod, descripcion) values (336,'CEREZO');
insert into colores(cod, descripcion) values (339,'GRIS MARA');
insert into colores(cod, descripcion) values (341,'MARRON MARMOLADO');
insert into colores(cod, descripcion) values (342,'VERDE PADDLE');
insert into colores(cod, descripcion) values (347,'AZUL DANUBIO');
insert into colores(cod, descripcion) values (354,'NEGRO FORJA');
insert into colores(cod, descripcion) values (364,'VERDE MOSTAZA');
insert into colores(cod, descripcion) values (370,'35 YY 81/233');
insert into colores(cod, descripcion) values (371,'BLANCO BRILLANTE');
insert into colores(cod, descripcion) values (374,'VERDE/BLANCO');
insert into colores(cod, descripcion) values (376,'BLANCO HIELO');
insert into colores(cod, descripcion) values (377,'33RR10/321');
insert into colores(cod, descripcion) values (378,'00NN62/200');
insert into colores(cod, descripcion) values (382,'30YY36/094');
insert into colores(cod, descripcion) values (383,'45YY83/062');
insert into colores(cod, descripcion) values (387,'NEGRO MARMOLADO');
insert into colores(cod, descripcion) values (391,'VERDE SEMIMATE');
insert into colores(cod, descripcion) values (392,'KHAKI');
insert into colores(cod, descripcion) values (393,'20YY51/098');
insert into colores(cod, descripcion) values (401,'PURPURA MATE');
insert into colores(cod, descripcion) values (402,'AZUL REAL MATE');
insert into colores(cod, descripcion) values (406,'NARANJA MATE');
insert into colores(cod, descripcion) values (408,'CELESTE PASTEL');
insert into colores(cod, descripcion, fecha_baja, motivo_baja) values (409,'CELESTE_PASTEL', date '2023-10-03', 'Repetido');
insert into colores(cod, descripcion) values (411,'AMARILLO MATE');
insert into colores(cod, descripcion) values (418,'ROJO HIERRO');
insert into colores(cod, descripcion) values (417,'AMARILLO CADMIO');
insert into colores(cod, descripcion) values (419,'GRIS MARMOLADO CLARO');
insert into colores(cod, descripcion) values (425,'NEGRO - AMARILLO');
insert into colores(cod, descripcion) values (424,'NEGRO - ROJO');
insert into colores(cod, descripcion) values (423,'AMARILLO - AZUL');
insert into colores(cod, descripcion) values (422,'BLANCO - ROJO');
insert into colores(cod, descripcion) values (421,'ROJO - VERDE');
insert into colores(cod, descripcion) values (420,'VERDE - ROJO');
insert into colores(cod, descripcion) values (426,'NEGRO - ROJO - NEGRO');
insert into colores(cod, descripcion) values (429,'VIOLETA CLARO');
insert into colores(cod, descripcion) values (430,'VIOLETA OSCURO');
insert into colores(cod, descripcion) values (434,'VERDE CROMO');
insert into colores(cod, descripcion) values (436,'AMARILLO CANARIO');
insert into colores(cod, descripcion) values (437,'ROJO - BLANCO - NEGRO');
insert into colores(cod, descripcion) values (450,'VIA LACTEA');
insert into colores(cod, descripcion) values (449,'ROSA PASTEL');
insert into colores(cod, descripcion) values (451,'CYAN/MAGENTA/AMARILLO');
insert into colores(cod, descripcion) values (209,'NEGRO SEMI MATE');
insert into colores(cod, descripcion) values (216,'NEGRO MATE');
insert into colores(cod, descripcion) values (225,'MORDORE');
insert into colores(cod, descripcion) values (273,'77');
insert into colores(cod, descripcion) values (278,'GRIS METALIZADO');
insert into colores(cod, descripcion) values (282,'GRIS GUIJARRO');
insert into colores(cod, descripcion) values (285,'GUATAMBU');
insert into colores(cod, descripcion) values (286,'LOURO');
insert into colores(cod, descripcion) values (292,'PHOTO MAGENTA');
insert into colores(cod, descripcion) values (316,'AMARILLO/NEGRO/MAGENTA/CYAN');
insert into colores(cod, descripcion) values (335,'BORDO');
insert into colores(cod, descripcion) values (338,'GRIS PLATA');
insert into colores(cod, descripcion) values (343,'ROJO COLONIAL');
insert into colores(cod, descripcion) values (350,'IMBUIA');
insert into colores(cod, descripcion) values (353,'90 YY 40/058');
insert into colores(cod, descripcion) values (362,'BEIGE OSCURO');
insert into colores(cod, descripcion) values (368,'81');
insert into colores(cod, descripcion) values (394,'BRONCE LEYENDA');
insert into colores(cod, descripcion) values (395,'P168 9C');
insert into colores(cod, descripcion) values (396,'AZUL ROJIZO');
insert into colores(cod, descripcion) values (398,'AZUL VERDOSO');
insert into colores(cod, descripcion) values (397,'AMARILLO CROMO MATE');
insert into colores(cod, descripcion) values (400,'VIOLETA MATE');
insert into colores(cod, descripcion) values (407,'AMARILLO-ROJO');
insert into colores(cod, descripcion) values (415,'ROJO BRILLANTE');
insert into colores(cod, descripcion) values (416,'VERDE BRILLANTE');
insert into colores(cod, descripcion) values (433,'AMARILLO FUERTE');
insert into colores(cod, descripcion) values (441,'D1');
insert into colores(cod, descripcion) values (446,'AZUL ZAFIRO');
insert into colores(cod, descripcion) values (447,'TIERRA SOMBRA TOSTADA');
insert into colores(cod, descripcion) values (453,'UNICROMATICA');
insert into colores(cod, descripcion) values (215,'ROJO BERMELLON');
insert into colores(cod, descripcion) values (226,'VERDE OPACO');
insert into colores(cod, descripcion) values (241,'ULTRAVIOLETA');
insert into colores(cod, descripcion) values (269,'ROJO FLUORESCENTE');
insert into colores(cod, descripcion) values (270,'AZUL FLUORESCENTE');
insert into colores(cod, descripcion) values (290,'PHOTO NEGRO');
insert into colores(cod, descripcion) values (291,'CYAN FOTOGRAFICO');
insert into colores(cod, descripcion) values (296,'ROJO METALIZADO');
insert into colores(cod, descripcion) values (297,'AZUL METALIZADO');
insert into colores(cod, descripcion) values (298,'VERDE METALIZADO');
insert into colores(cod, descripcion) values (302,'67');
insert into colores(cod, descripcion) values (306,'AMARILLO INTENSO');
insert into colores(cod, descripcion) values (310,'GUINDO');
insert into colores(cod, descripcion) values (312,'90 BG 72/088');
insert into colores(cod, descripcion) values (313,'20 YY 31/205');
insert into colores(cod, descripcion) values (314,'50 YY 33/065');
insert into colores(cod, descripcion) values (315,'30 YY 50/176');
insert into colores(cod, descripcion) values (320,'PASTEL');
insert into colores(cod, descripcion) values (322,'BLANCO SEMIMATE');
insert into colores(cod, descripcion) values (325,'GRIS TOPO');
insert into colores(cod, descripcion) values (349,'NEUTRO');
insert into colores(cod, descripcion) values (356,'AMARILLO NAPOLES');
insert into colores(cod, descripcion) values (363,'AMARILLO ORNAMENTAL');
insert into colores(cod, descripcion) values (365,'ROSADO METALIZADO');
insert into colores(cod, descripcion) values (366,'VIOLETA METALIZADO');
insert into colores(cod, descripcion) values (367,'LILA METALIZADO');
insert into colores(cod, descripcion) values (373,'VERDE FRONDA');
insert into colores(cod, descripcion) values (384,'30RR10/321');
insert into colores(cod, descripcion) values (386,'VERDE BOSQUE');
insert into colores(cod, descripcion) values (388,'SALMON CLARO');
insert into colores(cod, descripcion) values (404,'AMARILLO LIMON MATE');
insert into colores(cod, descripcion) values (405,'AZUL ULTRAMAR MATE');
insert into colores(cod, descripcion) values (413,'AMARILLO OCRE');
insert into colores(cod, descripcion) values (427,'30BB 62/044');
insert into colores(cod, descripcion) values (428,'50GY 76/146');
insert into colores(cod, descripcion) values (207,'CYAN CLARO');
insert into colores(cod, descripcion) values (208,'MAGENTA CLARO');
insert into colores(cod, descripcion) values (212,'AMARILLO MAIZ');
insert into colores(cod, descripcion) values (213,'VERDE AMAZONAS');
insert into colores(cod, descripcion) values (214,'PALTA');
insert into colores(cod, descripcion) values (232,'ROBLE');
insert into colores(cod, descripcion) values (246,'A1');
insert into colores(cod, descripcion) values (247,'A2');
insert into colores(cod, descripcion) values (248,'A3');
insert into colores(cod, descripcion) values (249,'B4');
insert into colores(cod, descripcion) values (252,'A4');
insert into colores(cod, descripcion) values (256,'AMARILLO Y NEGRO');
insert into colores(cod, descripcion) values (260,'AMARILLO-NEGRO');
insert into colores(cod, descripcion) values (265,'69');
insert into colores(cod, descripcion) values (276,'TECA');
insert into colores(cod, descripcion) values (277,'BLANCO PERLADO');
insert into colores(cod, descripcion) values (283,'PETIRIBI');
insert into colores(cod, descripcion) values (299,'AMARILLO METALIZADO');
insert into colores(cod, descripcion) values (311,'20 YY 83/100');
insert into colores(cod, descripcion) values (321,'PINO');
insert into colores(cod, descripcion) values (345,'MAGENTA FOTOGRAFICO');
insert into colores(cod, descripcion) values (348,'CAÑA DE AZUCAR');
insert into colores(cod, descripcion) values (351,'GRIS PLATINO');
insert into colores(cod, descripcion) values (358,'NEGRO HUMO');
insert into colores(cod, descripcion) values (359,'BLANCO SATINADO');
insert into colores(cod, descripcion) values (372,'16-1526 TCX');
insert into colores(cod, descripcion) values (375,'ONIX BEIGE');
insert into colores(cod, descripcion) values (410,'AZUL BRILLANTE');
insert into colores(cod, descripcion) values (431,'TURQUESA AZULADO');
insert into colores(cod, descripcion) values (435,'ROJO FUERTE');
insert into colores(cod, descripcion) values (438,'ARENADO');
insert into colores(cod, descripcion) values (439,'AMARILLO/VERDE');
insert into colores(cod, descripcion) values (454,'GRIS SOMBRA');
insert into colores(cod, descripcion) values (218,'GRIS MATE');
insert into colores(cod, descripcion) values (228,'HAYA');
insert into colores(cod, descripcion) values (231,'AZUL PIEDRA');
insert into colores(cod, descripcion) values (244,'C3');
insert into colores(cod, descripcion) values (245,'C4');
insert into colores(cod, descripcion) values (250,'B3');
insert into colores(cod, descripcion) values (251,'A3.5');
insert into colores(cod, descripcion) values (253,'B2');
insert into colores(cod, descripcion) values (261,'MAGENTA Y CYAN');
insert into colores(cod, descripcion) values (267,'ROSADO FLUORESCENTE');
insert into colores(cod, descripcion) values (268,'NARANJA FLUORESCENTE');
insert into colores(cod, descripcion) values (280,'VERDE CEMENTO');
insert into colores(cod, descripcion) values (294,'VERDE SECO');
insert into colores(cod, descripcion) values (301,'C2');
insert into colores(cod, descripcion) values (317,'VERDE CAQUI');
insert into colores(cod, descripcion) values (319,'VERDE MARMOLADO');
insert into colores(cod, descripcion) values (324,'VERDE ESPERANZA');
insert into colores(cod, descripcion) values (337,'TABACO');
insert into colores(cod, descripcion) values (346,'GRIS FOTOGRAFICO');
insert into colores(cod, descripcion) values (369,'SURTIDOS CON BRILLANTINA');
insert into colores(cod, descripcion) values (385,'NUDE');
insert into colores(cod, descripcion) values (389,'51 YY 74/066');
insert into colores(cod, descripcion) values (412,'AZUL DE PRUSIA');
insert into colores(cod, descripcion) values (440,'GRIS MEDIO');
insert into colores(cod, descripcion) values (210,'BLANCO Y AZUL');
insert into colores(cod, descripcion) values (224,'GRIS INTERIOR');
insert into colores(cod, descripcion) values (235,'GRIS CEMENTO');
insert into colores(cod, descripcion) values (236,'GRIS TORCAZA');
insert into colores(cod, descripcion) values (237,'VERDE PADEL');
insert into colores(cod, descripcion) values (242,'NOGAL BRIANZA');
insert into colores(cod, descripcion) values (243,'C1');
insert into colores(cod, descripcion) values (254,'TEJA');
insert into colores(cod, descripcion) values (275,'SEPIA');
insert into colores(cod, descripcion) values (318,'NEGRO FOTOGRAFICO');
insert into colores(cod, descripcion) values (333,'BEIGE MATE');
insert into colores(cod, descripcion) values (340,'GRIS HIELO');
insert into colores(cod, descripcion) values (344,'NEGRO BRILLANTE');
insert into colores(cod, descripcion) values (352,'AZUL REAL');
insert into colores(cod, descripcion) values (355,'CIAN');
insert into colores(cod, descripcion) values (357,'AZUL CERULEO');
insert into colores(cod, descripcion) values (361,'MUSGO ESPAÑOL');
insert into colores(cod, descripcion) values (360,'CORTE BRUTO');
insert into colores(cod, descripcion) values (379,'40YY79/028');
insert into colores(cod, descripcion) values (380,'44YY83/062');
insert into colores(cod, descripcion) values (381,'30YY56/060');
insert into colores(cod, descripcion) values (390,'CELESTE OSCURO');
insert into colores(cod, descripcion) values (399,'CARMIN MATE');
insert into colores(cod, descripcion) values (403,'ROJO MATE');
insert into colores(cod, descripcion) values (414,'SIENA TOSTADO');
insert into colores(cod, descripcion) values (432,'AZUL COBALTO');
insert into colores(cod, descripcion) values (445,'D2');
insert into colores(cod, descripcion) values (443,'TRANS GREY');
insert into colores(cod, descripcion) values (444,'D3');
insert into colores(cod, descripcion) values (442,'PEARL');
insert into colores(cod, descripcion) values (448,'BLANCO DE TITANIO');
insert into colores(cod, descripcion) values (452,'VERDE BOTELLA');
insert into colores(cod, descripcion) values (104,'COLOR');
insert into colores(cod, descripcion) values (105,'BLANCO Y NEGRO');
insert into colores(cod, descripcion) values (106,'CYAN');
insert into colores(cod, descripcion) values (107,'LADRILLO');
insert into colores(cod, descripcion) values (108,'AMARILLO, ROJO Y NEGRO');
insert into colores(cod, descripcion) values (109,'MOSTAZA');
insert into colores(cod, descripcion) values (110,'VERDE PETROLEO');
insert into colores(cod, descripcion) values (111,'TERRACOTA');
insert into colores(cod, descripcion) values (112,'1 TINTA');
insert into colores(cod, descripcion) values (113,'2 TINTAS');
insert into colores(cod, descripcion) values (114,'3 TINTAS');
insert into colores(cod, descripcion) values (115,'4 TINTAS');
insert into colores(cod, descripcion) values (116,'5 TINTAS');
insert into colores(cod, descripcion) values (117,'VERDE MANZANA');
insert into colores(cod, descripcion) values (118,'NOGAL');
insert into colores(cod, descripcion) values (119,'ROJO OXIDO');
insert into colores(cod, descripcion) values (120,'SERIE RAL');
insert into colores(cod, descripcion) values (121,'BRILLANTE');
insert into colores(cod, descripcion) values (122,'SEMIMATE');
insert into colores(cod, descripcion) values (123,'DORADO');
insert into colores(cod, descripcion) values (124,'VERDE SEÑAL');
insert into colores(cod, descripcion) values (125,'GRIS MARTILLADO');
insert into colores(cod, descripcion) values (126,'CANELA');
insert into colores(cod, descripcion) values (127,'MATIZADO');
insert into colores(cod, descripcion) values (128,'FLUORESCENTE');
insert into colores(cod, descripcion) values (129,'GRIS PIZARRA');
insert into colores(cod, descripcion) values (130,'CUERO');
insert into colores(cod, descripcion) values (131,'COLORADO');
insert into colores(cod, descripcion) values (132,'GRAFITADO');
insert into colores(cod, descripcion) values (133,'VERDE/AMARILLO');
insert into colores(cod, descripcion) values (134,'BORRA DE VINO');
insert into colores(cod, descripcion) values (135,'ROJO/BLANCO');
insert into colores(cod, descripcion) values (136,'UNIVERSAL');
insert into colores(cod, descripcion) values (137,'NARANJA CON REFLECTIVOS');
insert into colores(cod, descripcion) values (138,'AZUL OSCURO');
insert into colores(cod, descripcion) values (139,'BEIGE CLARO');
insert into colores(cod, descripcion) values (140,'BORDEAUX OSCURO');
insert into colores(cod, descripcion) values (141,'CELESTE CLARO');
insert into colores(cod, descripcion) values (142,'CREMA CLARO');
insert into colores(cod, descripcion) values (103,'NEGRO - CYAN');
insert into colores(cod, descripcion) values (2,'ALUMINIO');
insert into colores(cod, descripcion) values (3,'AMARILLO');
insert into colores(cod, descripcion) values (4,'AMARILLO CROMO');
insert into colores(cod, descripcion) values (5,'AZUL');
insert into colores(cod, descripcion) values (6,'AZUL BOLITA ');
insert into colores(cod, descripcion) values (7,'BEIGE');
insert into colores(cod, descripcion) values (8,'BLANCO');
insert into colores(cod, descripcion) values (9,'BLANCO/NEGRO');
insert into colores(cod, descripcion) values (10,'BLANCO/ROJO');
insert into colores(cod, descripcion) values (11,'CANARIO');
insert into colores(cod, descripcion) values (12,'CEDRO');
insert into colores(cod, descripcion) values (13,'CELESTE');
insert into colores(cod, descripcion) values (14,'CENIT');
insert into colores(cod, descripcion) values (15,'CENIZA');
insert into colores(cod, descripcion) values (16,'CREMA');
insert into colores(cod, descripcion) values (17,'GRIS');
insert into colores(cod, descripcion) values (18,'GRIS CENIZA');
insert into colores(cod, descripcion) values (19,'GRIS CLARO');
insert into colores(cod, descripcion) values (20,'MARFIL');
insert into colores(cod, descripcion) values (21,'MARRON');
insert into colores(cod, descripcion) values (22,'MARRON CLARO');
insert into colores(cod, descripcion) values (23,'NARANJA');
insert into colores(cod, descripcion) values (24,'NEGRO');
insert into colores(cod, descripcion) values (25,'OCRE');
insert into colores(cod, descripcion) values (26,'ORO');
insert into colores(cod, descripcion) values (27,'PLATINO');
insert into colores(cod, descripcion) values (28,'ROJO');
insert into colores(cod, descripcion) values (29,'ROJO TEJA');
insert into colores(cod, descripcion) values (30,'ROSADO');
insert into colores(cod, descripcion) values (31,'SIENA');
insert into colores(cod, descripcion) values (32,'TRANSPARENTE');
insert into colores(cod, descripcion) values (33,'VERDE');
insert into colores(cod, descripcion) values (34,'VERDE INGLES');
insert into colores(cod, descripcion) values (35,'VERDE MUSGO');
insert into colores(cod, descripcion) values (36,'VERDE TENIS');
insert into colores(cod, descripcion) values (37,'VIOLETA');
insert into colores(cod, descripcion) values (38,'GRIS ACORAZADO');
insert into colores(cod, descripcion) values (39,'ROJO CARMIN');
insert into colores(cod, descripcion) values (40,'INCOLORO');
insert into colores(cod, descripcion) values (41,'FUCSIA');
insert into colores(cod, descripcion) values (42,'BLANCO TIZA');
insert into colores(cod, descripcion) values (43,'ROBLE CLARO');
insert into colores(cod, descripcion) values (44,'ROBLE OSCURO');
insert into colores(cod, descripcion) values (45,'CAOBA');
insert into colores(cod, descripcion) values (46,'AZUL ELECTRICO');
insert into colores(cod, descripcion) values (47,'GRIS NACAR');
insert into colores(cod, descripcion) values (48,'AMBAR');
insert into colores(cod, descripcion) values (49,'PLATEADO');
insert into colores(cod, descripcion) values (50,'GRIS OSCURO');
insert into colores(cod, descripcion) values (51,'VERDE CLARO');
insert into colores(cod, descripcion) values (52,'VERDE OSCURO');
insert into colores(cod, descripcion) values (53,'MARRON OSCURO');
insert into colores(cod, descripcion) values (54,'AZUL MARINO');
insert into colores(cod, descripcion) values (55,'AZUL FRANCIA');
insert into colores(cod, descripcion) values (56,'TURQUESA');
insert into colores(cod, descripcion) values (57,'LILA');
insert into colores(cod, descripcion) values (58,'AMARILLO ORO');
insert into colores(cod, descripcion) values (59,'AMARILLO CLARO');
insert into colores(cod, descripcion) values (60,'AMARILLO FLUORESCENTE');
insert into colores(cod, descripcion) values (61,'HUESO');
insert into colores(cod, descripcion, fecha_baja, motivo_baja) values (1,'-----', date '2010-11-25', 'Ya no es más obligatorio el color en los artículos');
insert into colores(cod, descripcion) values (62,'NATURAL');
insert into colores(cod, descripcion) values (63,'BORDEAUX');
insert into colores(cod, descripcion) values (64,'TOSTADO');
insert into colores(cod, descripcion) values (65,'ROJO/NEGRO');
insert into colores(cod, descripcion) values (66,'ARENA');
insert into colores(cod, descripcion) values (67,'VERDE ESMERALDA');
insert into colores(cod, descripcion) values (68,'VERDE CON LINEA AMARILLA');
insert into colores(cod, descripcion) values (69,'BRONCE');
insert into colores(cod, descripcion) values (70,'PLATA');
insert into colores(cod, descripcion) values (71,'COBRE');
insert into colores(cod, descripcion) values (72,'ORO VIEJO');
insert into colores(cod, descripcion) values (73,'ORO BLANCO');
insert into colores(cod, descripcion) values (74,'ORO ROJO');
insert into colores(cod, descripcion) values (75,'MAGENTA/ROJO');
insert into colores(cod, descripcion) values (76,'CIAN/AZUL');
insert into colores(cod, descripcion) values (77,'ROJO CALIDO');
insert into colores(cod, descripcion) values (78,'RUBI');
insert into colores(cod, descripcion) values (79,'RODAMINA');
insert into colores(cod, descripcion) values (80,'PURPURA');
insert into colores(cod, descripcion) values (81,'TIERRA SIENA');
insert into colores(cod, descripcion) values (82,'TIERRA SOMBRA');
insert into colores(cod, descripcion) values (83,'TIERRA TOSTADA');
insert into colores(cod, descripcion) values (84,'TIERRA VERDE');
insert into colores(cod, descripcion) values (85,'ROSA VIEJO');
insert into colores(cod, descripcion) values (86,'BARNIZ PARA TINTA ORO');
insert into colores(cod, descripcion) values (87,'BARNIZ');
insert into colores(cod, descripcion) values (88,'MAGENTA');
insert into colores(cod, descripcion) values (89,'HABANO');
insert into colores(cod, descripcion) values (90,'BUFF');
insert into colores(cod, descripcion) values (91,'BERMELLON');
insert into colores(cod, descripcion) values (92,'MATE');
insert into colores(cod, descripcion) values (93,'AÑIL');
insert into colores(cod, descripcion) values (94,'CARMIN');
insert into colores(cod, descripcion) values (95,'MANTECA');
insert into colores(cod, descripcion) values (96,'VERDE AGUA');
insert into colores(cod, descripcion) values (97,'VERDE AGUA Y MANTECA');
insert into colores(cod, descripcion) values (98,'VERDE AGUA Y ROJO');
insert into colores(cod, descripcion) values (99,'MULTICOLOR');
insert into colores(cod, descripcion) values (100,'METALIZADO');
insert into colores(cod, descripcion) values (101,'GRIS PERLA');
insert into colores(cod, descripcion) values (102,'AZUL CIELO');
insert into colores(cod, descripcion) values (144,'OVO');
insert into colores(cod, descripcion) values (145,'SALMON');
insert into colores(cod, descripcion) values (146,'CROMADO');
insert into colores(cod, descripcion) values (150,'SURTIDOS');
insert into colores(cod, descripcion) values (151,'ANODIZADO NATURAL');
insert into colores(cod, descripcion) values (152,'CRUDO');
insert into colores(cod, descripcion) values (281,'AZUL CLARO');
insert into colores(cod, descripcion) values (154,'GLASE');
insert into colores(cod, descripcion) values (156,'VERDE OLIVA');
insert into colores(cod, descripcion) values (157,'AZUL SAJON');
insert into colores(cod, descripcion) values (159,'INVISIBLE');
insert into colores(cod, descripcion) values (160,'SEMI TRANSPARENTE');
insert into colores(cod, descripcion) values (161,'ROSA VETEADO');
insert into colores(cod, descripcion) values (162,'CARAMELO');
insert into colores(cod, descripcion) values (163,'VERDE ITALIA');
insert into colores(cod, descripcion) values (164,'RUBIO');
insert into colores(cod, descripcion) values (165,'CASTAÑO');
insert into colores(cod, descripcion) values (166,'EMPAVONADO');
insert into colores(cod, descripcion) values (167,'MIEL');
insert into colores(cod, descripcion) values (168,'ALMENDRA');
insert into colores(cod, descripcion) values (171,'BLANCO MATE');
insert into colores(cod, descripcion) values (172,'ROSADO VETEADO');
insert into colores(cod, descripcion) values (173,'MATIZ 62');
insert into colores(cod, descripcion) values (174,'MATIZ 65');
insert into colores(cod, descripcion) values (175,'MATIZ 66');
insert into colores(cod, descripcion) values (176,'AMARILLO OSCURO');
insert into colores(cod, descripcion) values (177,'GRAFITO');
insert into colores(cod, descripcion) values (178,'ROSA CLARO');
insert into colores(cod, descripcion) values (179,'BLANCO/CELESTE');
insert into colores(cod, descripcion) values (180,'ROJO Y VERDE');
insert into colores(cod, descripcion) values (181,'PIEL');
insert into colores(cod, descripcion) values (182,'BLANCO LECHE');
insert into colores(cod, descripcion) values (185,'CAMUFLADO');
insert into colores(cod, descripcion) values (186,'HUMO');
insert into colores(cod, descripcion) values (187,'OPACO');
insert into colores(cod, descripcion) values (188,'66');
insert into colores(cod, descripcion) values (189,'OSCURO');
insert into colores(cod, descripcion) values (190,'OSCURO MATE');
insert into colores(cod, descripcion) values (191,'VERDE LIMON');
insert into colores(cod, descripcion) values (192,'GRIS FORJA');
insert into colores(cod, descripcion) values (194,'VERDE FOLLAJE');
insert into colores(cod, descripcion) values (198,'62');
insert into colores(cod, descripcion) values (199,'65');
insert into colores(cod, descripcion) values (200,'CEREJEIRA');
insert into colores(cod, descripcion) values (202,'AHUMADO');
insert into colores(cod, descripcion) values (203,'SEMI MATE');
insert into colores(cod, descripcion) values (204,'ROJO ESCARLATA');
insert into colores(cod, descripcion) values (205,'MORADO');
insert into colores(cod, descripcion) values (227,'VERDE FLUORESCENTE');
insert into colores(cod, descripcion) values (229,'BICOLOR');
insert into colores(cod, descripcion) values (230,'AZUL PETROLEO');
insert into colores(cod, descripcion) values (233,'LAPACHO');
insert into colores(cod, descripcion) values (239,'ALTO BRILLO');
insert into colores(cod, descripcion) values (240,'AZUL/ROJO');
insert into colores(cod, descripcion) values (266,'GRIS HUMO');
insert into colores(cod, descripcion) values (279,'DURAZNO');
insert into colores(cod, descripcion) values (289,'GRIS URBANO');
