insert into odgs(odg, descripcion) values (383000,'OBRAS HIDRAULICAS, HIDROELECTRICAS Y SANITARIAS');
insert into odgs(odg, descripcion) values (384000,'INSTALACIONES DE TRANSMISION Y DISTRIBUCION');
insert into odgs(odg, descripcion) values (386000,'OTRAS CONSTRUCCIONES DE DOMINIO PRIVADO');
insert into odgs(odg, descripcion) values (387000,'VIAS DE COMUNICACION');
insert into odgs(odg, descripcion) values (349000,'OTROS EQUIPAMIENTOS EDUCACIONALES, CULTURALES Y RECREATIVOS');
insert into odgs(odg, descripcion) values (353000,'OTROS VEHICULOS, AUTOMOVILES');
insert into odgs(odg, descripcion) values (381000,'VIVIENDAS');
insert into odgs(odg, descripcion) values (219000,'OTROS SERVICIOS BASICOS');
insert into odgs(odg, descripcion) values (272000,'MANTENIMIENTO DE MAQUINAS Y EQUIPOS INDUSTRIALES');
insert into odgs(odg, descripcion) values (313000,'MAQUINAS Y EQUIPOS DE ELECTRICIDAD, GAS Y AGUA');
insert into odgs(odg, descripcion) values (341000,'EQUIPOS AUDIOVISUALES, DE FOTOGRAFIA Y SIMILARES');
insert into odgs(odg, descripcion) values (342000,'OBRAS DE ARTE Y PIEZAS DE MUSEO');
insert into odgs(odg, descripcion) values (344000,'MOBILIARIO AFECTADO ACTIV. EDUCACIONAL Y CULTURAL');
insert into odgs(odg, descripcion) values (362000,'MOTORES Y REPUESTOS MAYORES PARA MAQUINAS Y EQUIPOS DE OFICINA');
insert into odgs(odg, descripcion) values (247000,'CORRESPONDENCIA, ENCOMIENDAS CONTRATADAS DENTRO DEL PAIS');
insert into odgs(odg, descripcion) values (234000,'VIATICOS DENTRO DEL PAIS');
insert into odgs(odg, descripcion) values (114000,'PRODUCTOS AGROFORESTALES Y SUS MANUFACTURAS');
insert into odgs(odg, descripcion) values (153000,'PRODUCTOS VETERINARIOS');
insert into odgs(odg, descripcion) values (327000,'EQUIPAMIENTO PARA PREVENCION DE INCENDIO');
insert into odgs(odg, descripcion) values (332000,'EQUIPOS TECNICOS Y CIENTIFICOS');
insert into odgs(odg, descripcion) values (393000,'PROGRAMAS DE COMPUTACION Y SIMILARES');
insert into odgs(odg, descripcion) values (285000,'SERVICIOS INFORMATICOS Y ANEXOS');
insert into odgs(odg, descripcion) values (273000,'MANTENIMIENTO DE AUTOMOTORES');
insert into odgs(odg, descripcion) values (283000,'SERV. MEDICOS, SANITARIOS Y SOCIALES');
insert into odgs(odg, descripcion) values (292000,'CONTRATACION DE EQUIPOS SALAS Y CONEXOS');
insert into odgs(odg, descripcion) values (294000,'SERVICIOS DE ALIMENTACION');
insert into odgs(odg, descripcion) values (293000,'SERVICIOS PORTUARIOS');
insert into odgs(odg, descripcion) values (252000,'ARRENDAMIENTO DE INMUEBLES CONTRATADOS FUERA DEL PAIS');
insert into odgs(odg, descripcion) values (255000,'ARRENDAMIENTO DE EQUIPOS Y APARATOS DE AUDIO Y COMUNICACION');
insert into odgs(odg, descripcion) values (277000,'MANTENIMIENTO DE VIAS DE COMUNICACION');
insert into odgs(odg, descripcion) values (339000,'OTROS EQUIPAMIENTOS SANITARIOS Y CIENTIFICOS');
insert into odgs(odg, descripcion) values (391000,'EQUIPO MILITAR Y SEGURIDAD');
insert into odgs(odg, descripcion) values (284000,'SERVICIOS DE CAPACITACION');
insert into odgs(odg, descripcion) values (149000,'OTROS');
insert into odgs(odg, descripcion) values (296000,'GASTOS DE PROTOCOLO');
insert into odgs(odg, descripcion) values (394000,'ACTIVOS INTANGIBLES');
insert into odgs(odg, descripcion) values (269000,'OTROS TRIBUTOS, SEGUROS Y COMISIONES');
insert into odgs(odg, descripcion) values (357000,'EQUIPOS DE TRACCION Y ELEVACION');
insert into odgs(odg, descripcion) values (356000,'AERONAVES');
insert into odgs(odg, descripcion) values (21300,'SUELDO DEL GRADO DE FUNCIONES CONTRATADAS');
insert into odgs(odg, descripcion) values (42512,'COMP.ALIM.-INC.02');
insert into odgs(odg, descripcion) values (42522,'DIFERENCIA A TABLA');
insert into odgs(odg, descripcion) values (42630,'COMPENSACION ALTOS EJECUTIVOS');
insert into odgs(odg, descripcion) values (44001,'PRIMA POR ANTIGÜEDAD');
insert into odgs(odg, descripcion) values (46001,'DIFERENCIA POR SUBROGACION');
insert into odgs(odg, descripcion) values (48033,'DIFERENCIA AUMENTO ENERO/2010');
insert into odgs(odg, descripcion) values (51000,'DIETAS');
insert into odgs(odg, descripcion) values (72000,'HOGAR CONSTITUIDO');
insert into odgs(odg, descripcion) values (73000,'PRIMA POR NACIMIENTO');
insert into odgs(odg, descripcion) values (113000,'PRODUCTOS PECUARIOS');
insert into odgs(odg, descripcion) values (229000,'OTROS GASTOS EN PUBLICIDAD , IMPRESIONES Y ENCUADERNACIONES');
insert into odgs(odg, descripcion) values (213000,'SERVICIO DE ENERGIA ELECTRICA');
insert into odgs(odg, descripcion) values (11000,'SUELDO BÁSICO DE CARGOS');
insert into odgs(odg, descripcion) values (519000,'OTRAS TRANFERENCIAS CORRIENTES AL SECTOR PUBLICO');
insert into odgs(odg, descripcion) values (529000,'TRANSFERENCIAS CORRIENTES AL SECTOR PRIVADO NO INCLUYE ANTERIORES');
insert into odgs(odg, descripcion) values (539000,'TRANSFERENCIAS DE CAPITAL A OTROS ORG. DEL SECTOR PUBLICO');
insert into odgs(odg, descripcion) values (511015,'TRANSF CORRIENTE SECTOR PUB. PREMIOS LUCHA ANTIDRO Y LAV ACTIVOS');
insert into odgs(odg, descripcion) values (529018,'TRANSF CORRIENTE SECTOR PRIV. PREMIOS LUCHA ANTIDRO Y LAV ACTIVOS');
insert into odgs(odg, descripcion) values (581001,'CUOTAS ANUALES AFILIAC. ORGANISMOS INTERNACIONALES');
insert into odgs(odg, descripcion) values (581000,'TRANSFERENCIAS CORRIENTES A ORGANISMOS INTERNACIONALES');
insert into odgs(odg, descripcion) values (42611,'NIVEL RETRIBUTIVO MINIMO');
insert into odgs(odg, descripcion) values (591000,'OTRAS TRANSFERENCIAS CORRIENTES');
insert into odgs(odg, descripcion) values (515000,'TRANSFERENCIAS A GOBIERNO CENTRAL');
insert into odgs(odg, descripcion) values (514000,'TRANSFERENCIAS A GOBIERNO DEPARTAMENTAL ');
insert into odgs(odg, descripcion) values (435000,'PRESTAMOS OTORGADOS A CORTO PLAZO A GOBIERNOS DEPARTAMENTALES');
insert into odgs(odg, descripcion) values (491000,'FIDEICOMISOS');
insert into odgs(odg, descripcion) values (774000,'PERDIDAS EN OPERACIONES CAMBIARIAS');
insert into odgs(odg, descripcion) values (52003,'POR TRABAJO EN DIAS DE DESCANSO AL CESAR');
insert into odgs(odg, descripcion) values (42614,'PAGO DE SENTENCIA CON CONDENA A FUTURO DGC');
insert into odgs(odg, descripcion) values (42511,'COMP. ESPECIAL POR FUNCIONES ESPECIALM.ENCOM. (DISCRECIONAL)');
insert into odgs(odg, descripcion) values (578007,'SERVICIO ODONTOLOGICO, GUARDERIA Y OTROS');
insert into odgs(odg, descripcion) values (55003,'INCORP. PLUNA (PARA REG. 031) INC.02 UE008');
insert into odgs(odg, descripcion) values (55002,'INCORP.TRANS.AFE INC10 PG702UE1, A205L17930 PROY.INV888');
insert into odgs(odg, descripcion) values (576045,'INCENTIVO RETIRO FUNCIONARIOS DE AFE');
insert into odgs(odg, descripcion) values (354000,'EQUIPOS FERROVIARIOS');
insert into odgs(odg, descripcion) values (81000,'APORTE PATRONAL SISTEMA SEGURIDAD SOCIAL S/RETRIB.');
insert into odgs(odg, descripcion) values (82000,'OTROS APORTES PATRONALES SOBRE RETRIBUCIONES A FNV');
insert into odgs(odg, descripcion) values (87000,'APORTE PATRONAL A FONASA');
insert into odgs(odg, descripcion) values (42554,'COMPENSACION DESEMPEÑO ALTA CONDUCCION CO');
insert into odgs(odg, descripcion) values (42610,'COMPENSACION - SE ABSORBE');
insert into odgs(odg, descripcion) values (42620,'COMPENSACION PERSONAL');
insert into odgs(odg, descripcion) values (48007,'% DIFERENCIAL DEL AUMENTO - A.182 LEY 16.713');
insert into odgs(odg, descripcion) values (99000,'OTRAS RETRIBUCIONES');
insert into odgs(odg, descripcion) values (578002,'ASIGNACIONES FAMILIARES (HIJOS FUNC.PCOS.FALLECIDOS)');
insert into odgs(odg, descripcion) values (57001,'BECAS');
insert into odgs(odg, descripcion) values (57002,'PASANTIAS');
insert into odgs(odg, descripcion) values (51001,'HORAS DOCENTES');
insert into odgs(odg, descripcion) values (43023,'PRIMA P/REND.GRUPAL E INDV.-DGI Nº1)Y2)A23D166/005,A2L17706');
insert into odgs(odg, descripcion) values (57003,'EMPLEO JUVENIL');
insert into odgs(odg, descripcion) values (42574,'COMPENSACION ESPECIAL TAREAS ESPEC. O DE MAYOR RESPONS. AGESIC');
insert into odgs(odg, descripcion) values (236000,'OTROS GASTOS EN EXTERIOR (M/N Y M/E) TRASLADO, PARTIDA ESPECIAL');
insert into odgs(odg, descripcion) values (731000,'GASTOS CONFIDENCIALES');
insert into odgs(odg, descripcion) values (42509,'DIFERENCIA POR OCUPAR UNA VACANTE');
insert into odgs(odg, descripcion) values (57000,'BECAS DE TRABAJO Y PASANTIAS');
insert into odgs(odg, descripcion) values (42524,'DEDICACION EXCLUSIVA (SIRO)');
insert into odgs(odg, descripcion) values (553018,'INSTITUCIONES EN CONVENIO - JUNTA NACIONAL DE DROGAS');
insert into odgs(odg, descripcion) values (12000,'INCREMENTO POR MAYOR HORARIO PERMANENTE');
insert into odgs(odg, descripcion) values (13000,'DEDICACION TOTAL CARGOS PEMANENTES');
insert into odgs(odg, descripcion) values (21000,'SUELDO BASICO DE FUNCIONES CONTRATADAS');
insert into odgs(odg, descripcion) values (22000,'INCREMENTO POR MAYOR HORARIO PERMANENTE CONTRATADOS');
insert into odgs(odg, descripcion) values (31000,'RETRIBUCIONES ZAFRALES Y TEMPORALES');
insert into odgs(odg, descripcion) values (42010,'PRIMA TECNICA CON APORTES');
insert into odgs(odg, descripcion) values (42026,'COMPENSACIÓN DOCENTE');
insert into odgs(odg, descripcion) values (42033,'RETRIBUCIÓN COMPLEMENTARIA, FUNCIONES FUERA DE RESIDENCIA');
insert into odgs(odg, descripcion) values (42038,'COMPENSACIÓN PERSONAL TRANSITORIAS, SE ABSORBE CON ASCENSO');
insert into odgs(odg, descripcion) values (42046,'COMPENSACIÓN DISTRIBUCIÓN FONDO DE PARTICIPACIÓN');
insert into odgs(odg, descripcion) values (42105,'COMPENSACIÓN PERSONAL TRANSITORIA A7 LEY 17930');
insert into odgs(odg, descripcion) values (42513,'COMPENSACIÓN ESPECIAL DISCRECIONAL');
insert into odgs(odg, descripcion) values (43006,'COMPENSACIÓN POR TECNIF Y FISCALIZACIÓN DGCASINOS');
insert into odgs(odg, descripcion) values (48004,'AUMENTO ESP DEC 180/85');
insert into odgs(odg, descripcion) values (48018,'COMPLEMENTO POR NO ALCANZAR MINIMO DEC256/004');
insert into odgs(odg, descripcion) values (48021,'ADICRETNOM<=$13000INC2al1517al19y27(EXCPLyK)D259/05');
insert into odgs(odg, descripcion) values (67000,'COMPENSACIÓN POR ALIMENTACIÓN CON APORTES');
insert into odgs(odg, descripcion) values (69002,'COMPENSACIÓN POR PERFECCIONAMIENTO TÉCNICO-DGCASINOS');
insert into odgs(odg, descripcion) values (69003,'PRIMA POR ASISTENCIA SOCIAL-DGCASINOS');
insert into odgs(odg, descripcion) values (69004,'COMPENSACIÓN POR VESTIMENTA-DGCASINOS');
insert into odgs(odg, descripcion) values (555001,'TRANSF CORRIENT  INSTIT SIN FIN LUCRO - COMITE OLIMPICO URUGUAYO');
insert into odgs(odg, descripcion) values (793000,'INDEMINIZACIONES');
insert into odgs(odg, descripcion) values (711000,'SENTENCIAS JUDICIALES');
insert into odgs(odg, descripcion) values (38000,'PERSONAL ALTA ESPECIALIZACION ESTRATEGICA');
insert into odgs(odg, descripcion) values (31012,'CONTRATO ZAFRAL ART.8 LEY Nº 19996');
insert into odgs(odg, descripcion) values (42621,'COMPENSACION PERSONAL - CONVENIO COFE');
insert into odgs(odg, descripcion) values (56010,'SUBSIDIO POR ENFERMEDAD');
insert into odgs(odg, descripcion) values (42617,'PAGO SENTENCIA C/CONDENA A FUTURO NO ABS.C/ASC. A52 L17930');
insert into odgs(odg, descripcion) values (713000,'ACONTECIMIENTOS GRAVES O IMPREVISTOS');
insert into odgs(odg, descripcion) values (59000,'SUELDO ANUAL COMPLEMENTARIO');
insert into odgs(odg, descripcion) values (31004,'CONTRATO TEMPORAL DE DERECHO PUBLICO');
insert into odgs(odg, descripcion) values (11300,'SUELDO DEL GRADO');
insert into odgs(odg, descripcion) values (15000,'GASTOS DE REPRESENTACIÓN EN EL PAÍS CON APORTES');
insert into odgs(odg, descripcion) values (16000,'GASTOS DE REPRESENTACIÓN EN EL PAÍS 0%APORTES');
insert into odgs(odg, descripcion) values (33000,'TÉCNICOS CONTRATADOS C/FUNC.ALTA PRIORIDAD');
insert into odgs(odg, descripcion) values (42014,'COMPENSACIÓN POR PERMANENCIA A LA ORDEN');
insert into odgs(odg, descripcion) values (42087,'INCENTIVO AL RENDIMIENTO L16170 A19');
insert into odgs(odg, descripcion) values (42400,'COMPENSACIÓN AL CARGO');
insert into odgs(odg, descripcion) values (42510,'COMPENSACIÓN ESPECIAL POR FUNCIONES ESPECIALES');
insert into odgs(odg, descripcion) values (42517,'COMPENSACIÓN P/TAREAS ESPEC.MAYOR RESPONS.Y HORARIO VARIABLE');
insert into odgs(odg, descripcion) values (48026,'RECUP.SALARIAL ENERO/2007 A.454 L.17.930');
insert into odgs(odg, descripcion) values (48032,'RECUP.SALARIAL ENERO/2010');
insert into odgs(odg, descripcion) values (53000,'LICENCIAS GENERADAS Y NO GOZADAS');
insert into odgs(odg, descripcion) values (57006,'ADSCRIPTOS PRES.DE LA REPÚBLICA A65 L17930');
insert into odgs(odg, descripcion) values (71000,'PRIMA POR MATRIMONIO');
insert into odgs(odg, descripcion) values (74000,'PRESTACIONES POR HIJO');
insert into odgs(odg, descripcion) values (84000,'NO VIGENTE APORTE PATRONAL A DISSE');
insert into odgs(odg, descripcion) values (85000,'COMPLEMENTO CONTRIBUCIÓN PATRONAL CUOTA MUTUAL');
insert into odgs(odg, descripcion) values (86000,'APORTE PATRONAL A FONDO RECONV. LABORAL');
insert into odgs(odg, descripcion) values (91000,'RETRIBUCIONES DE EJERCICIOS VENCIDOS A49 L17930');
insert into odgs(odg, descripcion) values (92000,'PARTIDAS GLOBALES A DISTRIBUIR');
insert into odgs(odg, descripcion) values (92002,'PARTIDA GLOBAL A DISTRIBUIR P/ ADSCRIPTOS');
insert into odgs(odg, descripcion) values (92005,'PARTIDA GLOBAL PARA ESCALAFÓN CONDUCCIÓN');
insert into odgs(odg, descripcion) values (95005,'FONDO P/FINANCIAR FUNCIONES TRANSITORIAS Y DE CONDUCCIÓN');
insert into odgs(odg, descripcion) values (94000,'FDO P/FINANCIAR CARGOS O FUNC.A PERSONAS C/DISCAPACIDAD');
insert into odgs(odg, descripcion) values (95002,'FONDO PARA CONTRATOS TEMPORALES DCHO. PÚBLICO');
insert into odgs(odg, descripcion) values (99001,'PARTIDA PROYECTADA');
insert into odgs(odg, descripcion) values (513006,'ASISTENCIA FINANCIERA PRE-JUBILADOS BPS');
insert into odgs(odg, descripcion) values (575001,'SUBS.CARGOS POLITICOS/PART.CONF.85%');
insert into odgs(odg, descripcion) values (576038,'PRESTAC.15%S/RETRIBUC. FUNC.CON 60A69 AÑOS');
insert into odgs(odg, descripcion) values (576041,'INCENTIVO RETIRO>=58AÑOS31/12/05 Y CAUSAL/1/1/08');
insert into odgs(odg, descripcion) values (576043,'BENEFICIO PARA CAUSAHABIENTES DE INCENTIVOS');
insert into odgs(odg, descripcion) values (578001,'ASIGNACIONES FAMILIARES CLASES PASIVAS');
insert into odgs(odg, descripcion) values (578010,'HOGAR CONSTITUÍDO SUBS.CARGOS DE CONFIANZA');
insert into odgs(odg, descripcion) values (578097,'CANASTA FIN DE AÑO');
insert into odgs(odg, descripcion) values (43021,'PERSONAL SERV. SEGURIDAD INC 02 A 62 L17930');
insert into odgs(odg, descripcion) values (43024,'COMPENSACION ESCOLTA PRESIDENCIAL A114 L18172');
insert into odgs(odg, descripcion) values (45005,'QUEBRANTO DE CAJA');
insert into odgs(odg, descripcion) values (48017,'AUMENTO SALARIAL A PARTIR DEL 1/5/03 D191/003');
insert into odgs(odg, descripcion) values (48023,'RECUP SALARIAL INC 02 AL 27 (A454 L17930 EXCP PJ TCA CARGOS A388)');
insert into odgs(odg, descripcion) values (559000,'TRANSFERENCIAS CORRIENTES A OTRAS INSTIT. SIN FINES DE LUCRO');
insert into odgs(odg, descripcion) values (31006,'CONTRATO LABORAL A.54 L.18719');
insert into odgs(odg, descripcion) values (31007,'REGIMEN PROVISORIATO A.50 L.18719');
insert into odgs(odg, descripcion) values (42520,'COMPENSACIÓN ESPECIAL POR CUMPLIR CONDICIONES ESPECÍFICAS');
insert into odgs(odg, descripcion) values (42523,'FONDO PARTICIPACIÓN 100% Y CALIFICACIÓN SOBRE ANTIGÜEDAD');
insert into odgs(odg, descripcion) values (42530,'COMP. ESPECIAL POR HORARIO NOCTURNO O TRABAJO DÍAS INHÁBILES');
insert into odgs(odg, descripcion) values (55000,'RETRIBUCIONES REDISTRIBUÍDO INCOR.Y EXCEDENTARIOS-PROGS.800.');
insert into odgs(odg, descripcion) values (57005,'CONTRATOS DE TRABAJO A TÉRMINO A29A43L17556 D85/003(F11)');
insert into odgs(odg, descripcion) values (269001,'COMISIÓN POR RECAUDACIÓN DGI');
insert into odgs(odg, descripcion) values (269002,'COMISIÓN OPERADORES TURÍSTICOS POR REINTEGROS');
insert into odgs(odg, descripcion) values (591018,'FONDO REINTEGRO DE IMPUESTOS A TURISTAS');
insert into odgs(odg, descripcion) values (721000,'GASTOS EXTRAORDINARIOS');
insert into odgs(odg, descripcion) values (42017,'ASIDUIDAD CONVENIO COFE-MEF');
insert into odgs(odg, descripcion) values (771000,'CUENTAS INCOBRABLES');
insert into odgs(odg, descripcion) values (591001,'FONDO HIPICO');
insert into odgs(odg, descripcion) values (164000,'PETROLEO Y GAS NATURAL');
insert into odgs(odg, descripcion) values (258000,'ARRENDAMIENTO DE EQUIPOS DEL SECTOR SALUD');
insert into odgs(odg, descripcion) values (265000,'PRIMAS Y OTROS GASTOS DE SEGUROS CONTRATADOS FUERA DEL PAIS');
insert into odgs(odg, descripcion) values (295000,'MANTENIMIENTO DE REPRESENTACIONES EN EL EXTERIOR');
insert into odgs(odg, descripcion) values (297000,'DERECHOS Y REGALIAS');
insert into odgs(odg, descripcion) values (328000,'EQUIPAMIENTO PARA PREVENCION DE ROBOS');
insert into odgs(odg, descripcion) values (366000,'MOTORES Y REPUESTOS MAYORES PARA EQUIPOS DE TRACCION Y ELEVACION');
insert into odgs(odg, descripcion) values (42514,'COMP. ESPECIAL MAYOR RESPONSABILIDAD ORIGINADA PROVISORIATOS');
insert into odgs(odg, descripcion) values (63000,'SALARIO VACACIONAL');
insert into odgs(odg, descripcion) values (579001,'CONTRIBUCIONES DEPORTIV, ARTÍSTIC, CULTURAL.Y ATENCIÓN SALUD');
insert into odgs(odg, descripcion) values (31009,'CONTRATO DE TRABAJO A.92 L.19121');
insert into odgs(odg, descripcion) values (57011,'ADSCRIPTOS A57 L18719 DE INCISOS DISTINTO AL QUE LO CONTRATA');
insert into odgs(odg, descripcion) values (551015,'AGENCIA NACIONAL DE INVESTIGACION E INNOVACION');
insert into odgs(odg, descripcion) values (42616,'PAGO SENTENCIA C/CONDENA A FUTURO SE ABS.C/ASC. A52 L17930');
insert into odgs(odg, descripcion) values (399000,'OTROS BIENES DE USO');
insert into odgs(odg, descripcion) values (242000,'SERVICIOS DE MUDANZAS CONTRATADOS FUERA DEL PAIS');
insert into odgs(odg, descripcion) values (245000,'FLETES Y OTROS GASTOS CONTRATADOS DENTRO DEL PAIS');
insert into odgs(odg, descripcion) values (361000,'MOTORES Y REPUESTOS MAYORES PARA MAQUINAS Y EQUIPOS DE PRODUCCION');
insert into odgs(odg, descripcion) values (371000,'TIERRAS Y TERRENOS');
insert into odgs(odg, descripcion) values (222000,'PROPAGANDA');
insert into odgs(odg, descripcion) values (271000,'MANTENIMIENTO DE INMUEBLES E INSTALACIONES');
insert into odgs(odg, descripcion) values (123000,'CONFECCIONES TEXTILES');
insert into odgs(odg, descripcion) values (212000,'AGUA');
insert into odgs(odg, descripcion) values (214000,'GAS');
insert into odgs(odg, descripcion) values (221000,'PUBLICIDAD');
insert into odgs(odg, descripcion) values (223000,'IMPRESIONES, REPRODUCCIONES Y ENCUADERNACIONES');
insert into odgs(odg, descripcion) values (253000,'ARRENDAMIENTO DE EQUIPOS DE COMPUTACION');
insert into odgs(odg, descripcion) values (256000,'ARRENDAMIENTOS DE MAQUINAS Y EQUIPOS DE CONSTRUCCION');
insert into odgs(odg, descripcion) values (274000,'MANTENIMIENTO DE OTROS MEDIOS DE TRANSPORTE');
insert into odgs(odg, descripcion) values (311000,'AGROPECUARIA, DE PESCA Y DE MINERIA');
insert into odgs(odg, descripcion) values (312000,'MAQUINAS Y EQUIPOS DE INDUSTRIA MANUFACTURERA');
insert into odgs(odg, descripcion) values (364000,'MOTORES Y REPUESTOS MAYORES P/ EQUIPOS EDUCAC, CULTU Y RECREAT');
insert into odgs(odg, descripcion) values (246000,'FLETES Y OTROS GASTOS CONTRATADOS FUERA DEL PAIS');
insert into odgs(odg, descripcion) values (249000,'OTROS TRANSP. DE CARGA, SERV. COMPL. Y ALMACENAJE');
insert into odgs(odg, descripcion) values (266000,'COMISIONES BANCARIAS DENTRO DEL PAIS');
insert into odgs(odg, descripcion) values (291000,'SERVICIOS DE VIGILANCIA Y CUSTODIA');
insert into odgs(odg, descripcion) values (331000,'EQUIP. MEDICOS, QUIRURGICOS, DE LABORATORIO Y OTROS DE LA SALUD');
insert into odgs(odg, descripcion) values (379000,'OTROS, TIERRAS EDIFICIOS Y OTROS BIENES PREEXISTENT');
insert into odgs(odg, descripcion) values (389000,'OTRAS CONSTRUCCIONES DE DOMINIO PUBLICO');
insert into odgs(odg, descripcion) values (232000,'PASAJES AL EXTERIOR CONTRATADOS EN EL PAIS');
insert into odgs(odg, descripcion) values (233000,'PASAJES CONTRATADOS FUERA DEL PAIS');
insert into odgs(odg, descripcion) values (231000,'PASAJES DENTRO DEL PAIS');
insert into odgs(odg, descripcion) values (239000,'OTROS GASTOS DE TRASLADO');
insert into odgs(odg, descripcion) values (251000,'ARRENDAMIENTOS DE INMUEBLES CONTRATADOS DENTRO DEL PAIS');
insert into odgs(odg, descripcion) values (254000,'ARRENDAMIENTO DE EQUIPOS DE OFICINA');
insert into odgs(odg, descripcion) values (275000,'MANTENIMIENTO DE MOBILIARIO, EQUIPO DE OFICINA Y COMPUTACION');
insert into odgs(odg, descripcion) values (281000,'ESTUDIOS, INVESTIGACIONES Y PROYECTOS DE FACTIBILIDAD');
insert into odgs(odg, descripcion) values (282000,'SERV. DE PROFESIONALES Y TECNICOS');
insert into odgs(odg, descripcion) values (286000,'SERVICIOS ARTISTICOS Y SIMILARES');
insert into odgs(odg, descripcion) values (355000,'EMBARCACIONES');
insert into odgs(odg, descripcion) values (359000,'OTROS EQUIPOS DE TRANSPORTE, TRACCION, ELEVACION Y COMUNICACION');
insert into odgs(odg, descripcion) values (392000,'SEMOVIENTES');
insert into odgs(odg, descripcion) values (243000,'ALMACENAMIENTO CONTRATADO DENTRO DEL PAIS');
insert into odgs(odg, descripcion) values (299000,'OTROS SERVICIOS NO PERSONALES');
insert into odgs(odg, descripcion) values (321000,'MAQUINAS DE ESCRIBIR Y CALCULAR');
insert into odgs(odg, descripcion) values (322000,'EQUIPOS DE TELEFONIA Y SIMILARES');
insert into odgs(odg, descripcion) values (264000,'PRIMA Y OTROS GASTOS DE SEGUROS CONTRATADOS DENTRO DEL PAIS');
insert into odgs(odg, descripcion) values (319000,'OTROS, MAQUINARIAS Y EQUIPOS DE PRODUCCION');
insert into odgs(odg, descripcion) values (279000,'OTROS SERVICIOS DE MANTENIMIENTO, REP. MENORES Y LIMPIEZA');
insert into odgs(odg, descripcion) values (323000,'EQUIPOS DE INFORMATICA');
insert into odgs(odg, descripcion) values (211000,'TELEFONO, TELEGRAFO Y SIMILARES');
insert into odgs(odg, descripcion) values (241000,'SERVICIO DE MUDANZAS CONTRATADOS DENTRO DEL PAIS');
insert into odgs(odg, descripcion) values (343000,'EQUIPOS DEPORTIVOS Y RECREATIVOS');
insert into odgs(odg, descripcion) values (314000,'MAQUINAS Y EQUIPOS DE CONSTRUCCION');
insert into odgs(odg, descripcion) values (351000,'OMNIBUS');
insert into odgs(odg, descripcion) values (259000,'OTROS ARRENDAMIENTOS');
insert into odgs(odg, descripcion) values (263000,'TASAS Y OTROS');
insert into odgs(odg, descripcion) values (372000,'EDIFICIOS E INSTALACIONES');
insert into odgs(odg, descripcion) values (157000,'ARTICULOS DE CAUCHO');
insert into odgs(odg, descripcion) values (158000,'MUNICIONES Y EXPLOSIVOS');
insert into odgs(odg, descripcion) values (159000,'OTROS PROD. QUIMICOS DERIV. DEL PETROLEO Y ANEXOS');
insert into odgs(odg, descripcion) values (161000,'PROD. DE LOZA, CERAMICA Y SIMILARES');
insert into odgs(odg, descripcion) values (162000,'PRODUCTOS DE VIDRIO');
insert into odgs(odg, descripcion) values (163000,'MATERIALES DE CONSTRUCCION');
insert into odgs(odg, descripcion) values (169000,'OTROS PRODUCTOS MINERALES');
insert into odgs(odg, descripcion) values (171000,'PROD. BASICOS DE HIERRO Y ACERO');
insert into odgs(odg, descripcion) values (172000,'PROD. BASICOS METALICOS NO FERROSOS');
insert into odgs(odg, descripcion) values (173000,'ACCESORIOS METALICOS');
insert into odgs(odg, descripcion) values (174000,'ESTRUCTURAS METALICAS ACABADAS');
insert into odgs(odg, descripcion) values (176000,'HERRAMIENTAS MENORES');
insert into odgs(odg, descripcion) values (235000,'VIATICOS FUERA DEL PAIS');
insert into odgs(odg, descripcion) values (248000,'CORRESPONDENCIA, ENCOMIENDAS CONTRATADAS FUERA DEL PAIS');
insert into odgs(odg, descripcion) values (257000,'ARRENDAMIENTO DE EQUIPOS DE TRANSPORTE Y SIMILARES');
insert into odgs(odg, descripcion) values (194000,'ARTICULOS MENORES MEDICO QUIRURGICOS');
insert into odgs(odg, descripcion) values (195000,'ARTICULOS EDUCACIONALES, CULTURALES, DEPORTIVOS Y DE RECREACION');
insert into odgs(odg, descripcion) values (196000,'UTILES DE COCINA Y COMEDOR');
insert into odgs(odg, descripcion) values (197000,'ARTICULOS Y ACCESORIOS DE INFORMATICA');
insert into odgs(odg, descripcion) values (198000,'REPUESTOS Y ACCESORIOS');
insert into odgs(odg, descripcion) values (179000,'OTROS PRODUCTOS METALICOS');
insert into odgs(odg, descripcion) values (191000,'UTILES DE OFICINA');
insert into odgs(odg, descripcion) values (192000,'ELEMENTOS DE LIMPIEZA Y ASEO');
insert into odgs(odg, descripcion) values (352000,'CAMIONES');
insert into odgs(odg, descripcion) values (358000,'EQUIPOS DE COMUNICACIONES P/EQUIP. TRANS. TRAC. ELEV. Y COMUNIC.');
insert into odgs(odg, descripcion) values (363000,'MOTORES Y REPUESTOS MAYORES P/ EQUIPOS MEDICO-SANITARIO Y CIENTIF');
insert into odgs(odg, descripcion) values (365000,'MOTORES Y REPUESTOS MAYORES PARA EQUIPOS DE TRANSPORTE');
insert into odgs(odg, descripcion) values (367000,'MOTORES Y REPUESTOS MAYORES PARA EQUIPOS DE COMUNICACIONES');
insert into odgs(odg, descripcion) values (369000,'OTROS MOTORES Y REPUESTOS MAYORES');
insert into odgs(odg, descripcion) values (276000,'MANTENIMIENTO DE OTRAS MAQUINAS Y EQUIPOS');
insert into odgs(odg, descripcion) values (278000,'MANTENIMIENTO DE LIMPIEZA, ASEO Y FUMIGACION');
insert into odgs(odg, descripcion) values (289000,'OTROS SERVICIOS TECNICOS PROFESIONALES Y ARTISTICOS');
insert into odgs(odg, descripcion) values (324000,'EQUIPOS DE IMPRENTA, FOTOCOPIADORAS Y SIMILARES');
insert into odgs(odg, descripcion) values (325000,'EQUIPOS ELECTRICOS DE USO DOMESTICO');
insert into odgs(odg, descripcion) values (326000,'MOBILIARIO DE OFICINA');
insert into odgs(odg, descripcion) values (329000,'OTROS, MAQUINAS MOBILIARIO Y EQUIPOS DE OFICINA');
insert into odgs(odg, descripcion) values (112000,'ALIMENTOS PARA ANIMALES');
insert into odgs(odg, descripcion) values (156000,'PROD. PLASTICOS, ACRILICOS Y SIMILARES');
insert into odgs(odg, descripcion) values (193000,'ARTICULOS Y ACCESORIOS ELECTRICOS');
insert into odgs(odg, descripcion) values (111000,'ALIMENTOS PARA PERSONAS');
insert into odgs(odg, descripcion) values (115000,'MATERIA PRIMA AGROPECUARIA Y FORESTAL');
insert into odgs(odg, descripcion) values (119000,'OTROS PROD ALIMENTICIOS AGROPECUARIOS Y FORESTALES');
insert into odgs(odg, descripcion) values (121000,'HILADOS Y TELAS');
insert into odgs(odg, descripcion) values (122000,'PRENDAS DE VESTIR');
insert into odgs(odg, descripcion) values (124000,'CUERO, PIELES Y SIMILARES');
insert into odgs(odg, descripcion) values (129000,'OTROS PROD TEXTILES, PRENDAS DE VESTIR Y ART. CUERO');
insert into odgs(odg, descripcion) values (131000,'PAPELES DE OFICINA');
insert into odgs(odg, descripcion) values (132000,'PRODUCTOS DE PAPEL Y CARTON');
insert into odgs(odg, descripcion) values (133000,'FORMULARIOS, IMPRESOS Y SIMILARES');
insert into odgs(odg, descripcion) values (134000,'PRODUCTOS DE ARTES GRAFICAS');
insert into odgs(odg, descripcion) values (135000,'LIBROS, REVISTAS Y OTRAS PUBLICACIONES');
insert into odgs(odg, descripcion) values (136000,'ESPECIES TIMBRADAS Y VALORADAS');
insert into odgs(odg, descripcion) values (139000,'OTROS PROD. DE PAPEL LIBROS E IMPRESOS');
insert into odgs(odg, descripcion) values (141000,'COMBUSTIBLES DERIVADOS DEL PETROLEO');
insert into odgs(odg, descripcion) values (142000,'ELECTRICIDAD');
insert into odgs(odg, descripcion) values (143000,'SUPERGAS');
insert into odgs(odg, descripcion) values (144000,'CARBON MINERAL');
insert into odgs(odg, descripcion) values (145000,'PRODUCTOS ENERGETICOS DE ORIGEN VEGETAL');
insert into odgs(odg, descripcion) values (151000,'LUBRICANTES Y OTROS DERIVADOS DEL PETROLRO');
insert into odgs(odg, descripcion) values (152000,'PRODUCTOS MEDICINALES Y FARMACEUTICOS');
insert into odgs(odg, descripcion) values (154000,'COMPUESTOS QUIMICOS, TINTAS Y PINTURAS');
insert into odgs(odg, descripcion) values (155000,'ABONOS, FERTILIZANTES, FUMIGANTES ETC');
insert into odgs(odg, descripcion) values (199000,'OTROS BIENES DE CONSUMO');
insert into odgs(odg, descripcion) values (382000,'OTRAS EDIFICACIONES');
