insert into unidades_med(cod, descripcion, tipo) values (171,'STRIPS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (172,'SOBRES',NULL);
insert into unidades_med(cod, descripcion, tipo) values (175,'CARTUCHO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (176,'CM X CM X PLG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (177,'VALE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (178,'UNIDAD/G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (99,'MM X NRO.HILOS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (44,'LIBRILLO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (13,'MES',1);
insert into unidades_med(cod, descripcion, tipo) values (54,'MES/M2',NULL);
insert into unidades_med(cod, descripcion, tipo) values (19,'PAR',1);
insert into unidades_med(cod, descripcion, tipo) values (48,'PUESTA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (61,'SACHET',NULL);
insert into unidades_med(cod, descripcion, tipo) values (30,'TAMBOR',NULL);
insert into unidades_med(cod, descripcion, tipo) values (21,'TUBO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (10,'JUEGO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (179,'PATA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (180,'MEDIO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (181,'ENTERO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (182,'CUARTO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (183,'UM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (184,'UI',1);
insert into unidades_med(cod, descripcion, tipo) values (185,'TABLETA',1);
insert into unidades_med(cod, descripcion, tipo) values (186,'COMPRIMIDO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (187,'MOLDE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (188,'NOTA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (189,'MICRONES',1);
insert into unidades_med(cod, descripcion, tipo) values (190,'OVINO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (191,'BOVINO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (192,'ESPONJA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (193,'3',NULL);
insert into unidades_med(cod, descripcion, tipo) values (194,'OVILLO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (195,'PLAZA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (196,'N/MM',2);
insert into unidades_med(cod, descripcion, tipo) values (197,'GR',1);
insert into unidades_med(cod, descripcion, tipo) values (199,'M3/KM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (201,'BTU / H',1);
insert into unidades_med(cod, descripcion, tipo) values (202,'GB',1);
insert into unidades_med(cod, descripcion, tipo) values (203,'KB/S X KB/S X KB/S',NULL);
insert into unidades_med(cod, descripcion, tipo) values (204,'KHZ',NULL);
insert into unidades_med(cod, descripcion, tipo) values (205,'A X H',NULL);
insert into unidades_med(cod, descripcion, tipo) values (206,'KW',1);
insert into unidades_med(cod, descripcion, tipo) values (212,'OHM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (208,'CM X CM X MICRON',NULL);
insert into unidades_med(cod, descripcion, tipo) values (213,'KOHM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (214,'LICENCIA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (215,'SOFTWARE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (216,'BAJO VOLUMEN',NULL);
insert into unidades_med(cod, descripcion, tipo) values (217,'GRAN VOLUMEN',NULL);
insert into unidades_med(cod, descripcion, tipo) values (218,'N/PLG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (282,'MCG/DOSIS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (283,'UI/ML P',NULL);
insert into unidades_med(cod, descripcion, tipo) values (284,'UI/ML H',NULL);
insert into unidades_med(cod, descripcion, tipo) values (285,'UI/G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (286,'UI/200MG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (287,'UI/1ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (288,'UI/02ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (289,'UI/0.5ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (290,'UI(1,2MG)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (291,'UI VAD',NULL);
insert into unidades_med(cod, descripcion, tipo) values (293,'UI LEUC. N1',NULL);
insert into unidades_med(cod, descripcion, tipo) values (294,'U/G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (295,'U/ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (296,'U',NULL);
insert into unidades_med(cod, descripcion, tipo) values (297,'OO/O',NULL);
insert into unidades_med(cod, descripcion, tipo) values (298,'MUI',NULL);
insert into unidades_med(cod, descripcion, tipo) values (299,'MU',NULL);
insert into unidades_med(cod, descripcion, tipo) values (300,'MG/ML NAF',NULL);
insert into unidades_med(cod, descripcion, tipo) values (302,'DIA',2);
insert into unidades_med(cod, descripcion, tipo) values (303,'MG/MG AMOX/S',NULL);
insert into unidades_med(cod, descripcion, tipo) values (305,'MG/MG (T/U)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (306,'MG/MG (RIT/LOP)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (307,'MG/MG (NORG/ETINIL)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (309,'MG/MG (LAM/ZIDOV)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (310,'MG/MG (GLIB/FENF)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (311,'MG/MG (GEST/ETINIL)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (312,'MG/MG (FUROS/AMIL)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (313,'MG/MG (FUM/VIT.C)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (314,'MG/MG (FENIT/FENOB)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (315,'MG/MG (ESP/METRON)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (316,'MG/MG (DIC/PRID)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (317,'MG/MG (DIAZ/HOMA)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (318,'MG/MG (COLCH/DICLOF)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (319,'MG/MG (CLOX/DICICL)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (320,'MG/MG (CLORD/IMIP)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (322,'MG/MG (AMOX/CLAV)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (323,'MG/MG (AMO/SULB)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (324,'MG/MG (ALLOP/COLCH)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (325,'MG/MG (A/S)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (326,'MG/MG (A/B)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (327,'MG/MG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (328,'MG/G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (329,'MG/DSP',NULL);
insert into unidades_med(cod, descripcion, tipo) values (330,'MG/60ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (331,'MG/5ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (333,'MG/5MG(MET/GLI)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (334,'MG/5MG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (335,'MG/5G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (337,'MG/50ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (339,'MG/4ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (340,'MG/4G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (341,'MG/45ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (342,'MG/400ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (343,'MG/3ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (346,'MG/2ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (347,'MG/1ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (348,'MG/1G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (349,'MG/15ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (350,'MG/15G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (351,'MG/10ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (352,'MG/100ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (353,'MG/100M6',NULL);
insert into unidades_med(cod, descripcion, tipo) values (354,'MG/100MG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (355,'MG/100G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (356,'MG/0.125MG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (357,'MG/0.05MG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (359,'MG CA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (360,'MG BRO DOMI',NULL);
insert into unidades_med(cod, descripcion, tipo) values (362,'MG AMOX/S',NULL);
insert into unidades_med(cod, descripcion, tipo) values (363,'MG A/S',NULL);
insert into unidades_med(cod, descripcion, tipo) values (364,'MG (AMP/S)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (365,'MG (AMOX/CLAV)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (366,'MG (AMO/CLAV)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (367,'MEQ/L DE CA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (368,'MEQ/L',NULL);
insert into unidades_med(cod, descripcion, tipo) values (369,'MEQ DE CA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (371,'MCG/ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (372,'MCG/G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (373,'MCG/DSP',NULL);
insert into unidades_med(cod, descripcion, tipo) values (374,'MCG/D',NULL);
insert into unidades_med(cod, descripcion, tipo) values (375,'MCG/1ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (376,'MCG VAD',NULL);
insert into unidades_med(cod, descripcion, tipo) values (377,'MCG (EST+EST/NOR)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (379,'MCG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (381,'KU/G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (382,'KU/100G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (385,'KU',NULL);
insert into unidades_med(cod, descripcion, tipo) values (387,'HUMANO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (388,'GLUC-CA-K',NULL);
insert into unidades_med(cod, descripcion, tipo) values (389,'GLUC-CA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (391,'G/MG (DEX/SAL)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (392,'G/L DEXTROSA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (393,'G/G (CEFO/SULB)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (394,'G/G (AMOX/CLAV)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (395,'G/6ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (398,'G/3.96G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (399,'G/22.5MG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (400,'G/10ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (401,'G/100G',2);
insert into unidades_med(cod, descripcion, tipo) values (402,'G%',NULL);
insert into unidades_med(cod, descripcion, tipo) values (403,'G(LACTIC)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (404,'MAH',NULL);
insert into unidades_med(cod, descripcion, tipo) values (405,'MAH X V',NULL);
insert into unidades_med(cod, descripcion, tipo) values (408,'G/MG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (409,'UI/D',NULL);
insert into unidades_med(cod, descripcion, tipo) values (410,'%O',NULL);
insert into unidades_med(cod, descripcion, tipo) values (411,'/300MG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (412,'EL.U.',NULL);
insert into unidades_med(cod, descripcion, tipo) values (416,'MCI',NULL);
insert into unidades_med(cod, descripcion, tipo) values (415,'GRUESA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (417,'KUI',NULL);
insert into unidades_med(cod, descripcion, tipo) values (419,'MW',NULL);
insert into unidades_med(cod, descripcion, tipo) values (421,'TACHO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (422,'LUX',1);
insert into unidades_med(cod, descripcion, tipo) values (424,'KBPS',1);
insert into unidades_med(cod, descripcion, tipo) values (677,'MM / MM',2);
insert into unidades_med(cod, descripcion, tipo) values (679,'MADEJA',1);
insert into unidades_med(cod, descripcion, tipo) values (686,'UNIDADES',2);
insert into unidades_med(cod, descripcion, tipo) values (690,'COMPRIMIDO DISPERSABLE',2);
insert into unidades_med(cod, descripcion, tipo) values (691,'S/100ML',1);
insert into unidades_med(cod, descripcion, tipo) values (699,'GAL/H / NUMERO',1);
insert into unidades_med(cod, descripcion, tipo) values (701,'J',1);
insert into unidades_med(cod, descripcion, tipo) values (705,'PLG X PLG X MM',2);
insert into unidades_med(cod, descripcion, tipo) values (708,'BIMESTRAL',1);
insert into unidades_med(cod, descripcion, tipo) values (710,'HORAS',2);
insert into unidades_med(cod, descripcion, tipo) values (725,'W/HORA',2);
insert into unidades_med(cod, descripcion, tipo) values (729,'M2/L',1);
insert into unidades_med(cod, descripcion, tipo) values (738,'L/M2',1);
insert into unidades_med(cod, descripcion, tipo) values (739,'UNIDADES KREBS',1);
insert into unidades_med(cod, descripcion, tipo) values (741,'N',1);
insert into unidades_med(cod, descripcion, tipo) values (742,'GRADO',1);
insert into unidades_med(cod, descripcion, tipo) values (744,'K',1);
insert into unidades_med(cod, descripcion, tipo) values (746,'LM/W',1);
insert into unidades_med(cod, descripcion, tipo) values (751,'PL',1);
insert into unidades_med(cod, descripcion, tipo) values (752,'HP/V',1);
insert into unidades_med(cod, descripcion, tipo) values (753,'NUMERO X PLG',2);
insert into unidades_med(cod, descripcion, tipo) values (761,'MM/CANTIDAD',1);
insert into unidades_med(cod, descripcion, tipo) values (763,'MILLA NAUTICA',1);
insert into unidades_med(cod, descripcion, tipo) values (764,'BIBAG',1);
insert into unidades_med(cod, descripcion, tipo) values (768,'M X M X CM',1);
insert into unidades_med(cod, descripcion, tipo) values (773,'ENVASE PLASTICO',2);
insert into unidades_med(cod, descripcion, tipo) values (774,'BANDEJA PLASTICA',2);
insert into unidades_med(cod, descripcion, tipo) values (778,'KDA/ML',1);
insert into unidades_med(cod, descripcion, tipo) values (425,'PASTILLA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (426,'FRENCH',1);
insert into unidades_med(cod, descripcion, tipo) values (427,'TR',NULL);
insert into unidades_med(cod, descripcion, tipo) values (219,'MENSUAL',NULL);
insert into unidades_med(cod, descripcion, tipo) values (220,'DIAS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (221,'ANUAL',NULL);
insert into unidades_med(cod, descripcion, tipo) values (222,'MICROLITROS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (223,'RANGO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (226,'LAMINA X POZO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (225,'DETERMINACIONES',NULL);
insert into unidades_med(cod, descripcion, tipo) values (227,'PLACA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (228,'TIRA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (229,'DISCO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (230,'CM X CM X MM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (231,'12 TUBOS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (232,'24 TUBOS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (233,'KG/CM2',1);
insert into unidades_med(cod, descripcion, tipo) values (234,'UI/MICROLITRO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (235,'ML/MIN',1);
insert into unidades_med(cod, descripcion, tipo) values (236,'CM2',NULL);
insert into unidades_med(cod, descripcion, tipo) values (237,'GASA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (238,'MICRA',1);
insert into unidades_med(cod, descripcion, tipo) values (239,'APOSITO (A)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (240,'PARCHE (A)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (241,'INYECTABLE(AM)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (242,'CARAMELO (CA)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (243,'COMPRIMIDO (CM)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (244,'POLVO (CM)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (245,'COMPRIMIDO (CP)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (246,'INHALACION (D)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (247,'SOLUCION (D)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (248,'SUSPENSION (D)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (249,'APOSITO (G)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (250,'GOTA (G)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (251,'JABON (G)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (252,'JALEA (G)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (253,'POLVO (G)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (254,'POMADA (G)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (255,'SOLUCION (G)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (256,'SUSPENSION (G)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (257,'GOTAS (GT)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (258,'SOLUCION (L)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (259,'MECHA (M)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (260,'POLVO (MG)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (261,'GOTA (ML)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (262,'INHALACION (ML)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (263,'INYECTABLE (ML)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (264,'JALEA (ML)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (265,'POMADA (ML)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (266,'SOLUCION (ML)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (267,'SUSPENSION (ML)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (268,'OVULOS (OV)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (269,'APOSITO (PA)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (270,'PARCHE (PA)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (271,'APOSITO (RO)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (272,'POLVO (SO)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (273,'SUPOSITORIO (SU)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (274,'APOSITO (U)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (275,'CARAMELO (U)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (276,'COMPRIMIDO (U)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (277,'INHALACION (U)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (278,'POMADA (U)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (279,'SOLUCION (U)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (280,'PARCHE (SA)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (281,'G/100ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (428,'LB',NULL);
insert into unidades_med(cod, descripcion, tipo) values (429,'KV',1);
insert into unidades_med(cod, descripcion, tipo) values (430,'MM X MM X MICRON',NULL);
insert into unidades_med(cod, descripcion, tipo) values (431,'LAMINA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (433,'PESO URUGUAYO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (435,'MILISEGUNDO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (436,'MA',1);
insert into unidades_med(cod, descripcion, tipo) values (437,'KVA',1);
insert into unidades_med(cod, descripcion, tipo) values (438,'CAL 18-20',NULL);
insert into unidades_med(cod, descripcion, tipo) values (439,'CAL 16-14',NULL);
insert into unidades_med(cod, descripcion, tipo) values (440,'CAL 10-12',NULL);
insert into unidades_med(cod, descripcion, tipo) values (441,'CAL',NULL);
insert into unidades_med(cod, descripcion, tipo) values (442,'CFM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (443,'GAL/MIN',NULL);
insert into unidades_med(cod, descripcion, tipo) values (444,'PACK',NULL);
insert into unidades_med(cod, descripcion, tipo) values (445,'MONEDA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (446,'FICHA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (447,'CARRETE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (448,'LB/YD',NULL);
insert into unidades_med(cod, descripcion, tipo) values (449,'SET',1);
insert into unidades_med(cod, descripcion, tipo) values (451,'MM X MICRA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (452,'LOCION (ML)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (453,'GRADO X PLG',2);
insert into unidades_med(cod, descripcion, tipo) values (454,'VOLT X WATT',NULL);
insert into unidades_med(cod, descripcion, tipo) values (455,'PLG/N',NULL);
insert into unidades_med(cod, descripcion, tipo) values (456,'HZ',NULL);
insert into unidades_med(cod, descripcion, tipo) values (457,'SUSPENSION (MG)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (458,'JARABE (ML)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (459,'MOLAR',NULL);
insert into unidades_med(cod, descripcion, tipo) values (460,'INYECTABLE (IV)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (461,'INYECTABLE (IV/SC)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (462,'INYECTABLE (IM/IV)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (463,'INYECTABLE (IM)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (464,'INYECTABLE (SC)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (465,'INYECTABLE (IM/SC)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (471,'G/5ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (472,'INYECTABLE (IR)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (474,'INYECTABLE (IA/ID)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (475,'INYECTABLE (IM/IV/SC)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (478,'COMPRIMIDO (CP BLANDAS)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (479,'POMO (G)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (480,'EMULSION (ML)',NULL);
insert into unidades_med(cod, descripcion, tipo, fecha_baja, motivo_baja) values (481,'EMULSION',NULL, date '2005-09-06', '');
insert into unidades_med(cod, descripcion, tipo) values (482,'G/5G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (484,'INYECTABLE (IM/IV/IT)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (486,'COMPRIMIDO (LIB.MODIF.)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (487,'MCG/MG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (488,'L/DIA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (489,'ºC',1);
insert into unidades_med(cod, descripcion, tipo) values (490,'CM3',NULL);
insert into unidades_med(cod, descripcion, tipo) values (491,'KCAL',NULL);
insert into unidades_med(cod, descripcion, tipo) values (492,'CAMPOS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (494,'GAUCHE',1);
insert into unidades_med(cod, descripcion, tipo) values (495,'MICROF X V',NULL);
insert into unidades_med(cod, descripcion, tipo) values (496,'KM',NULL);
insert into unidades_med(cod, descripcion, tipo, fecha_baja, motivo_baja) values (497,'CANTIDAD X MM',NULL, date '2005-12-29', '');
insert into unidades_med(cod, descripcion, tipo) values (500,'NUMERO X MM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (502,'SEMESTRAL',NULL);
insert into unidades_med(cod, descripcion, tipo) values (503,'CUADROS POR PULGADA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (504,'G/M',NULL);
insert into unidades_med(cod, descripcion, tipo) values (505,'WATTS (RMS)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (506,'PH',NULL);
insert into unidades_med(cod, descripcion, tipo) values (507,'M3/H',1);
insert into unidades_med(cod, descripcion, tipo) values (513,'PIE X M X MICRONES',NULL);
insert into unidades_med(cod, descripcion, tipo, fecha_baja, motivo_baja) values (514,'HHHHHHHHHHHHHHH',NULL, date '2006-05-18', '');
insert into unidades_med(cod, descripcion, tipo, fecha_baja, motivo_baja) values (516,'AAAAAAAA',NULL, date '2013-07-05', 'mal definido');
insert into unidades_med(cod, descripcion, tipo) values (517,'NUMERO X NUMERO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (518,'COPIAS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (519,'COPIA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (520,'KCAL/H',NULL);
insert into unidades_med(cod, descripcion, tipo) values (521,'G/M2',1);
insert into unidades_med(cod, descripcion, tipo) values (523,'TON X KM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (524,'CHARRIERE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (527,'AMPOLLA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (528,'MICROMOLES',NULL);
insert into unidades_med(cod, descripcion, tipo) values (529,'SPRAY',NULL);
insert into unidades_med(cod, descripcion, tipo) values (531,'INHALADOR',NULL);
insert into unidades_med(cod, descripcion, tipo) values (532,'PARCHE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (533,'MG (CA)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (534,'YARDA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (702,'MM X MM X GALGA',1);
insert into unidades_med(cod, descripcion, tipo) values (707,'MPA',1);
insert into unidades_med(cod, descripcion, tipo) values (714,'CM/CM',2);
insert into unidades_med(cod, descripcion, tipo) values (743,'KN',1);
insert into unidades_med(cod, descripcion, tipo) values (756,'MICROGRAMO',1);
insert into unidades_med(cod, descripcion, tipo) values (765,'IMPRESIONES',1);
insert into unidades_med(cod, descripcion, tipo) values (769,'MM X KG/M',2);
insert into unidades_med(cod, descripcion, tipo) values (771,'BOTELLA',2);
insert into unidades_med(cod, descripcion, tipo) values (772,'ENVASE',2);
insert into unidades_med(cod, descripcion, tipo) values (776,'CH',1);
insert into unidades_med(cod, descripcion, tipo) values (779,'GEL (ML)',1);
insert into unidades_med(cod, descripcion, tipo) values (795,'MCI/ML',1);
insert into unidades_med(cod, descripcion, tipo) values (799,'NUMERO DE CONO',1);
insert into unidades_med(cod, descripcion, tipo) values (809,'LUMEN',1);
insert into unidades_med(cod, descripcion, tipo) values (810,'MS',1);
insert into unidades_med(cod, descripcion, tipo) values (811,'GRAMPAS',1);
insert into unidades_med(cod, descripcion, tipo) values (813,'LIBRETA',1);
insert into unidades_med(cod, descripcion, tipo) values (814,'CREMA (ML)',1);
insert into unidades_med(cod, descripcion, tipo) values (818,'CANT BAT./AH',2);
insert into unidades_med(cod, descripcion, tipo) values (822,'BARRIL',1);
insert into unidades_med(cod, descripcion, tipo) values (823,'PASCAL',1);
insert into unidades_med(cod, descripcion, tipo) values (535,'GAUGE X PLG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (536,'G.L.',NULL);
insert into unidades_med(cod, descripcion, tipo) values (537,'POLVO CUTANEO (G)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (538,'GAUGE X MM',1);
insert into unidades_med(cod, descripcion, tipo) values (539,'CREMA (G)',2);
insert into unidades_med(cod, descripcion, tipo) values (541,'BEBIBLE (ML)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (542,'NEBULIZACION (ML)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (543,'MG/HORA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (547,'COMPRIMIDO (SUBLINGUAL)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (548,'JALEA UROLOGICA (ML)',NULL);
insert into unidades_med(cod, descripcion, tipo, fecha_baja, motivo_baja) values (549,'JALEA UROL. (ML)',NULL, date '2006-10-05', '');
insert into unidades_med(cod, descripcion, tipo) values (551,'GRANULADO (G)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (552,'MG/MCG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (553,'DETERMINACION',1);
insert into unidades_med(cod, descripcion, tipo) values (554,'MM X MICRONES',NULL);
insert into unidades_med(cod, descripcion, tipo, fecha_baja, motivo_baja) values (555,'ESPIGA X DIAMETRO X HILOS',NULL, date '2006-10-24', '');
insert into unidades_med(cod, descripcion, tipo) values (556,'PLG X PLG - NUMERO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (557,'NANOMOLES',NULL);
insert into unidades_med(cod, descripcion, tipo) values (559,'MCG (LEV NOR/ET EST)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (560,'M X CM',2);
insert into unidades_med(cod, descripcion, tipo) values (561,'MINUTOS',1);
insert into unidades_med(cod, descripcion, tipo) values (562,'PLG-CM-MM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (563,'FRASCO X ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (564,'MM - UM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (565,'US',NULL);
insert into unidades_med(cod, descripcion, tipo) values (566,'MM X G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (567,'BAR',1);
insert into unidades_med(cod, descripcion, tipo) values (568,'LOG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (572,'TARJETAS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (574,'TUBOS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (575,'FRENCH X CM',2);
insert into unidades_med(cod, descripcion, tipo) values (578,'CM X M X CALIBRE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (579,'DALTON',NULL);
insert into unidades_med(cod, descripcion, tipo) values (580,'POZO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (582,'NTU',NULL);
insert into unidades_med(cod, descripcion, tipo) values (584,'CASSETTE',NULL);
insert into unidades_med(cod, descripcion, tipo, fecha_baja, motivo_baja) values (585,'MM',NULL, date '2012-11-22', 'Repetido con cod. 68');
insert into unidades_med(cod, descripcion, tipo, fecha_baja, motivo_baja) values (586,'CALIDAD DEL AGUA',NULL, date '2007-09-24', '');
insert into unidades_med(cod, descripcion, tipo) values (587,'TIROS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (588,'MESH',1);
insert into unidades_med(cod, descripcion, tipo) values (591,'JERINGA PRELLENADA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (592,'MM X CM X CM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (593,'TUBINO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (594,'MMOL/L',NULL);
insert into unidades_med(cod, descripcion, tipo) values (595,'PLG X NUMERO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (596,'JERINGA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (597,'MCG/DIA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (599,'GALON',NULL);
insert into unidades_med(cod, descripcion, tipo) values (600,'PAÑO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (602,'KM / MESES',NULL);
insert into unidades_med(cod, descripcion, tipo) values (603,'NUMERO DE TUBOS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (605,'GAUGE X CM',1);
insert into unidades_med(cod, descripcion, tipo) values (606,'BIMENSUAL',NULL);
insert into unidades_med(cod, descripcion, tipo) values (607,'CUATRIMESTRAL',NULL);
insert into unidades_med(cod, descripcion, tipo) values (608,'M2/G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (609,'P.T (PIE TABLON)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (615,'º (GRADOS)',1);
insert into unidades_med(cod, descripcion, tipo) values (618,'LLAVE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (621,'MM - CM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (629,'ARMAS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (632,'EMULSION (G)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (643,'COMPRIMIDO MASTICABLE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (645,'MM X MM X CALIBRE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (647,'TORX',NULL);
insert into unidades_med(cod, descripcion, tipo) values (649,'MILIMOLAR',NULL);
insert into unidades_med(cod, descripcion, tipo) values (655,'CARACTER',NULL);
insert into unidades_med(cod, descripcion, tipo) values (656,'-----/POTENCIA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (657,'-----/W',NULL);
insert into unidades_med(cod, descripcion, tipo) values (664,'POLVO EFERVESCENTE (G)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (683,'DECIBEL',1);
insert into unidades_med(cod, descripcion, tipo) values (680,'CL',1);
insert into unidades_med(cod, descripcion, tipo) values (695,'PLACAS',2);
insert into unidades_med(cod, descripcion, tipo) values (696,'CELDA',1);
insert into unidades_med(cod, descripcion, tipo) values (697,'MB/S',1);
insert into unidades_med(cod, descripcion, tipo) values (706,'G/CM3',1);
insert into unidades_med(cod, descripcion, tipo) values (709,'TON/M3',1);
insert into unidades_med(cod, descripcion, tipo) values (720,'KV - KVA',2);
insert into unidades_med(cod, descripcion, tipo) values (722,'CUPO/ANUAL',1);
insert into unidades_med(cod, descripcion, tipo) values (727,'KG/M2',1);
insert into unidades_med(cod, descripcion, tipo) values (740,'M2 MEMBRANA/M2 SUPERFICIE',1);
insert into unidades_med(cod, descripcion, tipo) values (754,'FUNDA',1);
insert into unidades_med(cod, descripcion, tipo) values (757,'UNIDAD(ES)',1);
insert into unidades_med(cod, descripcion, tipo) values (762,'CPS',1);
insert into unidades_med(cod, descripcion, tipo) values (766,'TARRO',1);
insert into unidades_med(cod, descripcion, tipo) values (777,'GHZ/DBI',2);
insert into unidades_med(cod, descripcion, tipo) values (782,'OZ X PLG',2);
insert into unidades_med(cod, descripcion, tipo) values (784,'CIRCULAR',2);
insert into unidades_med(cod, descripcion, tipo) values (785,'ANILLO VAGINAL',2);
insert into unidades_med(cod, descripcion, tipo) values (791,'POTENCIA REACTIVA',3);
insert into unidades_med(cod, descripcion, tipo) values (794,'CM H20',1);
insert into unidades_med(cod, descripcion, tipo) values (796,'BILLETES',1);
insert into unidades_med(cod, descripcion, tipo) values (801,'UA',1);
insert into unidades_med(cod, descripcion, tipo) values (802,'SESION(ES)',1);
insert into unidades_med(cod, descripcion, tipo) values (808,'M3/MIN',1);
insert into unidades_med(cod, descripcion, tipo) values (812,'NM3',1);
insert into unidades_med(cod, descripcion, tipo) values (817,'VOLT X AMP',2);
insert into unidades_med(cod, descripcion, tipo) values (819,'PLG / AGUJEROS',2);
insert into unidades_med(cod, descripcion, tipo) values (820,'>100',2);
insert into unidades_med(cod, descripcion, tipo) values (824,'MM - MM - MM',1);
insert into unidades_med(cod, descripcion, tipo) values (825,'W/W',1);
insert into unidades_med(cod, descripcion, tipo) values (614,'CM - NRO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (617,'MG/ML - UG/ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (626,'MICROPLACA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (628,'SOLUCION LP (SC/IM)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (652,'GEL (G)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (658,'PRUEBA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (673,'TRIMESTRAL',NULL);
insert into unidades_med(cod, descripcion, tipo) values (681,'CPS-°C',2);
insert into unidades_med(cod, descripcion, tipo) values (682,'MBITS',1);
insert into unidades_med(cod, descripcion, tipo) values (687,'KVAR/V',1);
insert into unidades_med(cod, descripcion, tipo) values (693,'--',4);
insert into unidades_med(cod, descripcion, tipo) values (694,'POCILLO',1);
insert into unidades_med(cod, descripcion, tipo) values (713,'TB',1);
insert into unidades_med(cod, descripcion, tipo) values (723,'CM X CM X CM',2);
insert into unidades_med(cod, descripcion, tipo) values (726,'M X MM X CM',1);
insert into unidades_med(cod, descripcion, tipo) values (748,'°',1);
insert into unidades_med(cod, descripcion, tipo) values (780,'PAQUETE(ES)',1);
insert into unidades_med(cod, descripcion, tipo) values (783,'CREDITO',1);
insert into unidades_med(cod, descripcion, tipo) values (788,'UG',1);
insert into unidades_med(cod, descripcion, tipo) values (790,'MEDIO PAR',1);
insert into unidades_med(cod, descripcion, tipo) values (797,'PLG X PLG X MICRA',1);
insert into unidades_med(cod, descripcion, tipo) values (800,'SESIONES',1);
insert into unidades_med(cod, descripcion, tipo) values (803,'AH',1);
insert into unidades_med(cod, descripcion, tipo) values (804,'BPM',1);
insert into unidades_med(cod, descripcion, tipo) values (815,'ACEITE (ML)',1);
insert into unidades_med(cod, descripcion, tipo) values (821,'DPI',1);
insert into unidades_med(cod, descripcion, tipo) values (619,'W/---',NULL);
insert into unidades_med(cod, descripcion, tipo) values (623,'ML - L',NULL);
insert into unidades_med(cod, descripcion, tipo) values (624,'F X CM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (627,'COMPRIMIDO (LP)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (631,'PF (PICOFARADIO)',NULL);
insert into unidades_med(cod, descripcion, tipo) values (665,'CABEZA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (666,'KILOMETRO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (671,'HECTAREA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (684,'----',1);
insert into unidades_med(cod, descripcion, tipo) values (685,'---',3);
insert into unidades_med(cod, descripcion, tipo) values (688,'CELSIUS',1);
insert into unidades_med(cod, descripcion, tipo) values (698,'GAL/H',1);
insert into unidades_med(cod, descripcion, tipo) values (711,'BARRIL DE PETROLEO',1);
insert into unidades_med(cod, descripcion, tipo) values (712,'LOTE',1);
insert into unidades_med(cod, descripcion, tipo) values (716,'GOTAS (ML)',1);
insert into unidades_med(cod, descripcion, tipo) values (719,'MP',1);
insert into unidades_med(cod, descripcion, tipo) values (724,'-----/MM',2);
insert into unidades_med(cod, descripcion, tipo) values (728,'M2/KG',1);
insert into unidades_med(cod, descripcion, tipo) values (731,'M2 K/W',1);
insert into unidades_med(cod, descripcion, tipo) values (732,'M2 C/W',1);
insert into unidades_med(cod, descripcion, tipo) values (733,'M2 °C/W',1);
insert into unidades_med(cod, descripcion, tipo) values (734,'M2 /KG',1);
insert into unidades_med(cod, descripcion, tipo) values (735,'W/M2K',1);
insert into unidades_med(cod, descripcion, tipo) values (736,'°C',1);
insert into unidades_med(cod, descripcion, tipo) values (737,'HSA',1);
insert into unidades_med(cod, descripcion, tipo) values (747,'H',1);
insert into unidades_med(cod, descripcion, tipo) values (749,'V/MM',1);
insert into unidades_med(cod, descripcion, tipo) values (755,'MM/G',2);
insert into unidades_med(cod, descripcion, tipo) values (767,'BIDON',1);
insert into unidades_med(cod, descripcion, tipo) values (770,'ENVASE FLEXIBLE',1);
insert into unidades_med(cod, descripcion, tipo) values (781,'HILOS',1);
insert into unidades_med(cod, descripcion, tipo) values (786,'G/MOL',1);
insert into unidades_med(cod, descripcion, tipo) values (787,'MG PT/I',1);
insert into unidades_med(cod, descripcion, tipo) values (792,'MG/DL',1);
insert into unidades_med(cod, descripcion, tipo) values (793,'MMHG',1);
insert into unidades_med(cod, descripcion, tipo) values (798,'PULGADA X PULGADA X MICRA',1);
insert into unidades_med(cod, descripcion, tipo) values (805,'M/S',1);
insert into unidades_med(cod, descripcion, tipo) values (816,'40 - 2.34 (GLU - CLORURO)',2);
insert into unidades_med(cod, descripcion, tipo) values (613,'CST-ºC',NULL);
insert into unidades_med(cod, descripcion, tipo) values (616,'KUI/ML- MG/ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (620,'PERSONAS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (622,'MICROMETRO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (625,'GAUGE',1);
insert into unidades_med(cod, descripcion, tipo) values (630,'CASILLAS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (633,'JORNAL',NULL);
insert into unidades_med(cod, descripcion, tipo) values (642,'M X M X M',2);
insert into unidades_med(cod, descripcion, tipo) values (646,'GAUCHE X PLG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (651,'KB',NULL);
insert into unidades_med(cod, descripcion, tipo) values (653,'PALABRA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (654,'FOJA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (670,'MILIMETROS/FRENCH',NULL);
insert into unidades_med(cod, descripcion, tipo) values (689,'SEMANA',1);
insert into unidades_med(cod, descripcion, tipo) values (718,'PAGINAS POR MINUTO',1);
insert into unidades_med(cod, descripcion, tipo) values (721,'MBPS',1);
insert into unidades_med(cod, descripcion, tipo) values (730,'KG/M3',1);
insert into unidades_med(cod, descripcion, tipo) values (745,'LM',1);
insert into unidades_med(cod, descripcion, tipo) values (750,'KA',1);
insert into unidades_med(cod, descripcion, tipo) values (758,'AÑOS',1);
insert into unidades_med(cod, descripcion, tipo) values (759,'MESES',1);
insert into unidades_med(cod, descripcion, tipo) values (760,'% (V/V)',1);
insert into unidades_med(cod, descripcion, tipo) values (775,'BLOQUE',2);
insert into unidades_med(cod, descripcion, tipo) values (789,'MICROMOL',1);
insert into unidades_med(cod, descripcion, tipo) values (806,'M/MIN',1);
insert into unidades_med(cod, descripcion, tipo) values (807,'CICLOS/MIN',1);
insert into unidades_med(cod, descripcion, tipo) values (826,'FRENCH - MM',1);
insert into unidades_med(cod, descripcion, tipo) values (2,'AÑO',1);
insert into unidades_med(cod, descripcion, tipo) values (3,'BARRA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (4,'BOBINA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (5,'CAJA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (6,'FRASCO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (7,'G',1);
insert into unidades_med(cod, descripcion, tipo) values (8,'HORA HOMBRE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (9,'HOJA',1);
insert into unidades_med(cod, descripcion, tipo) values (11,'KG',1);
insert into unidades_med(cod, descripcion, tipo) values (12,'L',1);
insert into unidades_med(cod, descripcion, tipo) values (14,'M',1);
insert into unidades_med(cod, descripcion, tipo) values (15,'M2',1);
insert into unidades_med(cod, descripcion, tipo) values (16,'M3',1);
insert into unidades_med(cod, descripcion, tipo) values (17,'POMO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (18,'PAQUETE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (20,'ROLLO',1);
insert into unidades_med(cod, descripcion, tipo) values (22,'UNIDAD',1);
insert into unidades_med(cod, descripcion, tipo) values (23,'DOCENA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (24,'ATADO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (25,'LATA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (26,'ML',1);
insert into unidades_med(cod, descripcion, tipo) values (27,'CC',1);
insert into unidades_med(cod, descripcion, tipo) values (28,'LIBRA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (29,'AVIO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (31,'CONO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (32,'KIT',NULL);
insert into unidades_med(cod, descripcion, tipo) values (33,'VIAL',NULL);
insert into unidades_med(cod, descripcion, tipo) values (34,'CLIP',NULL);
insert into unidades_med(cod, descripcion, tipo) values (35,'STRIP',NULL);
insert into unidades_med(cod, descripcion, tipo) values (36,'DOSIS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (37,'TON',1);
insert into unidades_med(cod, descripcion, tipo) values (38,'5',NULL);
insert into unidades_med(cod, descripcion, tipo) values (39,'PIE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (40,'GLOBAL',NULL);
insert into unidades_med(cod, descripcion, tipo) values (41,'TON.DE MEZCLA ASF.A MODIF',NULL);
insert into unidades_med(cod, descripcion, tipo) values (42,'BOLSA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (43,'MILLAR',NULL);
insert into unidades_med(cod, descripcion, tipo) values (45,'%',1);
insert into unidades_med(cod, descripcion, tipo) values (46,'HORA',1);
insert into unidades_med(cod, descripcion, tipo) values (47,'M3 X KILOMETRO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (49,'MES/KM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (50,'M3 DE MATERIAL EXTRAIDO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (51,'CM / M2',NULL);
insert into unidades_med(cod, descripcion, tipo) values (52,'MB',1);
insert into unidades_med(cod, descripcion, tipo) values (55,'CM',1);
insert into unidades_med(cod, descripcion, tipo) values (56,'M3-KM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (57,'BLISTER',NULL);
insert into unidades_med(cod, descripcion, tipo) values (58,'ONZA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (59,'POTE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (60,'SOBRE',NULL);
insert into unidades_med(cod, descripcion, tipo) values (62,'CUADRA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (63,'CONTENEDOR',NULL);
insert into unidades_med(cod, descripcion, tipo) values (64,'GALON U.S.',NULL);
insert into unidades_med(cod, descripcion, tipo) values (65,'V',1);
insert into unidades_med(cod, descripcion, tipo) values (66,'W',1);
insert into unidades_med(cod, descripcion, tipo) values (67,'VISCOSIDAD',1);
insert into unidades_med(cod, descripcion, tipo) values (68,'MM',1);
insert into unidades_med(cod, descripcion, tipo) values (69,'A',1);
insert into unidades_med(cod, descripcion, tipo) values (70,'L/MIN',1);
insert into unidades_med(cod, descripcion, tipo) values (71,'PLG',1);
insert into unidades_med(cod, descripcion, tipo) values (72,'MM2',1);
insert into unidades_med(cod, descripcion, tipo) values (73,'SECCION CUADRADA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (74,'ML/L',2);
insert into unidades_med(cod, descripcion, tipo) values (75,'M X MM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (76,'VOL',NULL);
insert into unidades_med(cod, descripcion, tipo) values (77,'MG/ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (78,'MEQ C/DOSIS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (79,'UI/GOTAS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (80,'UI/ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (81,'G/ML',1);
insert into unidades_med(cod, descripcion, tipo) values (1,'-----',2);
insert into unidades_med(cod, descripcion, tipo) values (82,'MG',1);
insert into unidades_med(cod, descripcion, tipo) values (83,'KU/ML',NULL);
insert into unidades_med(cod, descripcion, tipo) values (84,'KU/GR',NULL);
insert into unidades_med(cod, descripcion, tipo) values (85,'A MAXIMO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (86,'UF',NULL);
insert into unidades_med(cod, descripcion, tipo) values (87,'KA X A',NULL);
insert into unidades_med(cod, descripcion, tipo) values (88,'MM2 X M',NULL);
insert into unidades_med(cod, descripcion, tipo) values (89,'PLG X CM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (90,'PLG X M',NULL);
insert into unidades_med(cod, descripcion, tipo) values (91,'G/L',1);
insert into unidades_med(cod, descripcion, tipo) values (92,'ASA',NULL);
insert into unidades_med(cod, descripcion, tipo, fecha_baja, motivo_baja) values (93,'MM X MM X 5',NULL, date '2005-01-26', 'NO CORRESPONDE');
insert into unidades_med(cod, descripcion, tipo) values (94,'PLG X CM X CM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (95,'UNIDAD X M',NULL);
insert into unidades_med(cod, descripcion, tipo) values (96,'UNIDAD X MM2',NULL);
insert into unidades_med(cod, descripcion, tipo) values (97,'MM X CM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (98,'MM X PLG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (100,'UNIDAD X W',NULL);
insert into unidades_med(cod, descripcion, tipo) values (101,'CM X CM X 5',NULL);
insert into unidades_med(cod, descripcion, tipo) values (102,'M X M X MM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (103,'PIE CUBICO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (104,'MM X MM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (105,'ML X MM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (106,'CM X MM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (107,'M X M',2);
insert into unidades_med(cod, descripcion, tipo) values (108,'MM X 5',NULL);
insert into unidades_med(cod, descripcion, tipo) values (109,'FM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (110,'OHM X V',NULL);
insert into unidades_med(cod, descripcion, tipo) values (111,'CM X M',NULL);
insert into unidades_med(cod, descripcion, tipo) values (112,'NRO DE TUBO',NULL);
insert into unidades_med(cod, descripcion, tipo) values (113,'WATMAN',NULL);
insert into unidades_med(cod, descripcion, tipo) values (114,'TELA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (115,'GHZ',1);
insert into unidades_med(cod, descripcion, tipo) values (116,'NRO. X MM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (117,'MOHM',1);
insert into unidades_med(cod, descripcion, tipo) values (118,'RPM',1);
insert into unidades_med(cod, descripcion, tipo) values (119,'DB',1);
insert into unidades_med(cod, descripcion, tipo) values (120,'MHZ',1);
insert into unidades_med(cod, descripcion, tipo, fecha_baja, motivo_baja) values (121,':C',1, date '2015-08-04', 'mal definida');
insert into unidades_med(cod, descripcion, tipo) values (122,'PLG X M X M',NULL);
insert into unidades_med(cod, descripcion, tipo) values (123,'MIN',NULL);
insert into unidades_med(cod, descripcion, tipo) values (124,'CM X CM',2);
insert into unidades_med(cod, descripcion, tipo, fecha_baja, motivo_baja) values (125,'CM X CM X CM',1, date '2019-03-27', 'no corresponde el tipo');
insert into unidades_med(cod, descripcion, tipo) values (126,'PSI',1);
insert into unidades_med(cod, descripcion, tipo) values (127,'TON X PLG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (128,'HP',1);
insert into unidades_med(cod, descripcion, tipo) values (129,'MG/L',NULL);
insert into unidades_med(cod, descripcion, tipo) values (130,'PLG X PLG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (131,'S',NULL);
insert into unidades_med(cod, descripcion, tipo) values (132,'BRIX',NULL);
insert into unidades_med(cod, descripcion, tipo) values (133,'%/G/L',NULL);
insert into unidades_med(cod, descripcion, tipo) values (134,'ONZA LIQUIDA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (135,'PLG A PLG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (136,'MILIF X V',NULL);
insert into unidades_med(cod, descripcion, tipo) values (137,'PF X V',NULL);
insert into unidades_med(cod, descripcion, tipo) values (138,'PLG X PLG X M',1);
insert into unidades_med(cod, descripcion, tipo) values (139,'NRO. X MM2',NULL);
insert into unidades_med(cod, descripcion, tipo) values (140,'V X HZ',NULL);
insert into unidades_med(cod, descripcion, tipo) values (141,'UL',NULL);
insert into unidades_med(cod, descripcion, tipo) values (142,'L/H',1);
insert into unidades_med(cod, descripcion, tipo) values (143,'NM',1);
insert into unidades_med(cod, descripcion, tipo) values (144,'PLG X W',NULL);
insert into unidades_med(cod, descripcion, tipo) values (145,'MM X MM X MM',2);
insert into unidades_med(cod, descripcion, tipo) values (146,'PLG X PLG X PLG',2);
insert into unidades_med(cod, descripcion, tipo) values (147,'M X MM X MM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (148,'PLG X NRO. DIENTES',NULL);
insert into unidades_med(cod, descripcion, tipo) values (149,'NRO',1);
insert into unidades_med(cod, descripcion, tipo) values (150,'TON X H',NULL);
insert into unidades_med(cod, descripcion, tipo) values (151,'MM X PLG X PLG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (152,'CM X PLG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (153,'MM X M',NULL);
insert into unidades_med(cod, descripcion, tipo) values (154,'A X V',NULL);
insert into unidades_med(cod, descripcion, tipo) values (155,'CM X CM X M',NULL);
insert into unidades_med(cod, descripcion, tipo) values (156,'PLG X MM',NULL);
insert into unidades_med(cod, descripcion, tipo) values (157,'MM/PLG',NULL);
insert into unidades_med(cod, descripcion, tipo) values (158,'KV X A',NULL);
insert into unidades_med(cod, descripcion, tipo) values (159,'MM X MM X M',NULL);
insert into unidades_med(cod, descripcion, tipo) values (160,'M X CM X CM',2);
insert into unidades_med(cod, descripcion, tipo) values (161,'TON X PLG X M',NULL);
insert into unidades_med(cod, descripcion, tipo) values (162,'PPM',1);
insert into unidades_med(cod, descripcion, tipo) values (163,'KG/M',NULL);
insert into unidades_med(cod, descripcion, tipo) values (164,'OHM X W',NULL);
insert into unidades_med(cod, descripcion, tipo) values (165,'NF X V',NULL);
insert into unidades_med(cod, descripcion, tipo) values (166,'PIE X M',NULL);
insert into unidades_med(cod, descripcion, tipo) values (167,'G/G',NULL);
insert into unidades_med(cod, descripcion, tipo) values (168,'PORCION',NULL);
insert into unidades_med(cod, descripcion, tipo) values (169,'RANGO DE NUMEROS',NULL);
insert into unidades_med(cod, descripcion, tipo) values (170,'SLIDES',NULL);
insert into unidades_med(cod, descripcion, tipo) values (667,'MM / -----',NULL);
insert into unidades_med(cod, descripcion, tipo) values (668,'MM / DIOPTRIA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (669,'CAPSULA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (672,'ML X MICRA',NULL);
insert into unidades_med(cod, descripcion, tipo) values (674,'°BAUME',2);
insert into unidades_med(cod, descripcion, tipo) values (675,'°BRIX',2);
insert into unidades_med(cod, descripcion, tipo) values (678,'BLOCK',1);
insert into unidades_med(cod, descripcion, tipo) values (692,'PAGINA',1);
insert into unidades_med(cod, descripcion, tipo) values (700,'PLG2',1);
insert into unidades_med(cod, descripcion, tipo) values (703,'HOJAS',1);
insert into unidades_med(cod, descripcion, tipo) values (704,'GRAPAS',1);
insert into unidades_med(cod, descripcion, tipo) values (715,'QUINCENAL',1);
insert into unidades_med(cod, descripcion, tipo) values (717,'CUPO/MES',1);
