insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,2,5,'FOTOCOPIADORAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,2,6,'EQUIPOS DE SERVICIO ELECTRICO Y ACCESORIOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,4,1,'SERVICIO DE MUDANZA DENTRO DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,4,5,'FLETES Y OTROS GASTOS DE TRANSPORTE TERRESTRE EN EL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,3,1,'EQUIPOS HOSPITALARIOS Y DE LABORATORIO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,3,2,'EQUIPOS ODONTOLOGICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,3,9,'OTROS EQUIPOS TECNICOS Y CIENTIFICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,5,1,'ARRENDAMIENTO DE INMUEBLES DENTRO DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (3,5,3,'ARRENDAMIENTO DE EQUIPOS DE COMPUTACION', date '2010-07-14', 'Ver Rama 3-10 (TIC)');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,5,4,'ARRENDAMIENTO DE EQUIPOS DE SERVICIOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,4,1,'EQUIPOS DE AUDIO Y VIDEO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,4,2,'EQUIPOS DE CINEMATOGRAFIA Y FOTOGRAFIA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,4,3,'INSTRUMENTOS MUSICALES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,4,4,'OBRAS DE ARTE Y PIEZAS DE MUSEO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,4,5,'EQUIPOS DEPORTIVOS Y RECREATIVOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,5,1,'AUTOMOVILES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,5,2,'CAMIONETAS, JEEPS Y SIMILARES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,5,3,'OMNIBUS Y MINIBUSES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,5,4,'VEHICULO PESADO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,5,5,'CICLOMOTORES Y BICICLETAS');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (4,6,1,'TELEGRAFICAS, TELEX', date '2010-03-12', 'Reestructura del Catálogo TIC');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (4,6,2,'TELEFONICAS', date '2010-03-12', 'Reestructura del Catálogo TIC');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,6,3,'EQUIPOS DE RADIOCOMUNICACIONES Y ACCESORIOS');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (4,6,4,'TELEVISIVAS', date '2010-03-12', 'Reestructura de Catálogo TIC');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,6,5,'EQUIPOS DE SEÑALIZACION PARA TRANSPORTE TERRESTRE');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,7,1,'PARA MAQUINAS Y EQUIP.DE GENERACION Y TRANSMISION ENERGETICA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,7,2,'PARA OTRAS MAQUINAS Y EQUIPOS DE PRODUCCION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,7,3,'PARA MAQUINAS Y EQUIPOS DE OFICINA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,7,4,'PARA EQUIPOS MEDICOS, SANITARIOS, ODONTOLOGICOS, CIENTIFICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,7,5,'PARA EQUIPOS EDUCACIONALES, CULTURALES Y RECREATIVOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,7,6,'PARA MAQUINAS Y EQUIPOS DE TRANSPORTE');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,7,7,'PARA MAQUINAS Y EQUIPOS DE COMUNICACIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,8,1,'MOBILIARIO DE MADERA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,8,2,'MOBILIARIO DE METAL');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,8,3,'MOBILIARIO DE MADERA Y METAL');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,2,1,'EDIFICIOS PARA OFICINA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,2,2,'VIVIENDA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,2,3,'EDIFICIOS PARA USOS PRODUCTIVOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,2,4,'EDIFICIOS PARA ENSEÑANZA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,2,5,'EDIFICIOS PARA SALUD');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,2,6,'EDIFICIOS PARA FINES DE DEFENSA Y SEGURIDAD');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,1,1,'ALIMENTOS DE ORIGEN AGROPECUARIO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,1,2,'ALIMENTOS PROVENIENTES DE LA PESCA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,1,3,'ALIMENTOS MANUFACTURADOS Y BEBIDAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,1,4,'MATERIAS PRIMAS DE ORIGEN PECUARIO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,1,5,'MATERIAS PRIMAS DE ORIGEN AGRICOLA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,1,6,'MATERIAS PRIMAS DE ORIGEN FORESTAL');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,1,7,'MATERIAS PRIMAS DE ORIGEN MARITIMO, FLUVIAL Y LACUSTRE');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,1,8,'SEMILLAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,2,1,'MINERALES METALICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,2,2,'PIEDRA, ARCILLA, ARENA Y SIMILARES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,2,3,'PETROLEO CRUDO Y GAS NATURAL');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,2,4,'OTROS MINERALES NO METALICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,3,1,'HILADOS, TELAS Y OTROS PRODUCTOS TEXTILES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,3,2,'PRENDAS DE VESTIR');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,3,3,'CALZADO DE CUERO Y DEPORTIVO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,4,1,'PAPELES DE OFICINA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,4,2,'PAPELES Y TARJETAS DE COMPUTACION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,4,3,'FORMULARIOS Y OTROS IMPRESOS SIMILARES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,4,4,'PRODUCTOS DE PAPEL Y CARTON');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,4,5,'PRODUCTOS DE ARTES GRAFICAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,4,6,'LIBROS, REVISTAS Y OTRAS PUBLICACIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,4,7,'ESPECIES TIMBRADAS Y VALORADAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,5,1,'COMBUSTIBLES DERIVADOS DEL PETROLEO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,5,2,'ELECTRICIDAD');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,5,3,'GAS');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (2,5,4,'SUPERGAS', date '2012-07-06', 'VER 2-5-1');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,5,5,'CARBON MINERAL');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,5,6,'PRODUCTOS ENERGETICOS DE ORIGEN VEGETAL');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,6,1,'ARTICULOS DE CAUCHO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,6,2,'LUBRICANTES Y GRASAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,6,3,'ABONOS, FERTILIZANTES, INSECTICIDAS Y SIMILARES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,6,4,'PRODUCTOS QUIMICOS, MEDICINALES Y FARMACEUTICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,6,5,'PRODUCTOS SANITARIOS, DE LIMPIEZA, PINTURAS Y CONEXOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,6,6,'PRODUCTOS PLASTICOS Y SIMILARES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,6,7,'MUNICIONES , EXPLOSIVOS Y ACCESORIOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,6,8,'PRODUCTOS BITUMINOSOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,7,1,'PRODUCTOS DE ARCILLA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,7,2,'PRODUCTOS DE VIDRIO Y CRISTAL');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,7,3,'CEMENTO, CAL, TIZA, YESO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,7,4,'PRODUCTOS DE LOZA, PORCELANA Y SIMILARES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,7,5,'PRODUCTOS DE MADERA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,8,1,'PRODUCTOS BASICOS DE HIERRO Y ACERO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,8,2,'PRODUCTOS BASICOS METALICOS NO FERROSOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,8,3,'ACCESORIOS METALICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,8,4,'ESTRUCTURAS METALICAS ACABADAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,8,6,'HERRAMIENTAS MENORES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,9,1,'UTILES DE OFICINA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,9,2,'UTILES DE LIMPIEZA Y ASEO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,9,3,'UTILES Y ACCESORIOS ELECTRICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,9,4,'UTILES MENORES MEDICO-QUIRURGICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,9,5,'UTILES DEPORTIVOS Y DE RECREO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,9,6,'UTILES DE COCINA Y COMEDOR');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,9,7,'UTILES EDUCACIONALES Y CULTURALES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,1,1,'TELEFONO, TELEGRAFO Y SIMILARES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,1,2,'TRANSPORTE DE CORRESPONDENCIA Y ENCOMIENDAS DENTRO DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,1,3,'TRANSPORTE DE CORRESPONDENCIA Y ENCOMIENDAS FUERA DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,1,4,'APROVISIONAMIENTO DE AGUA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,2,1,'PUBLICIDAD Y PROPAGANDA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,6,6,'EQUIPOS DE SEÑALIZACION PARA TRANSPORTE MARITIMO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,5,8,'GRUAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,8,2,'CONTRATACION DE SERVICIOS MEDICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,1,8,'VIAS FERREAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,9,1,'INSTALACIONES INDUSTRIALES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,9,2,'INSTALACIONES DOMICILIARIAS Y DE OFICINAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,10,1,'ACCESORIOS NAUTICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,9,10,'UTILES TECNICOS Y CIENTIFICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,4,10,'MEJORAMIENTO DE BARRIO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,9,3,'INSTALACIONES PARA COMUNICACIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,2,10,'CIMENTACIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,12,1,'PARA MAQUINAS Y EQUIPOS DE TRANSPORTE');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,12,2,'PARA MAQUINAS Y EQUIPOS DE OFICINA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,12,3,'PARA MAQUINAS Y EQUIPOS DE PRODUCCION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,12,4,'OTROS REPUESTOS Y ACCESORIOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,12,5,'PARA EQUIPOS MEDICOS, SANITARIOS, ODONTOLOGICOS, CIENTIFICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,10,2,'OTROS PRODUCTOS DE USO MARINO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,1,'FARMACOS ANTI-INFECCIOSOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,2,'FARMACOS ANTISEPTICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,3,'FARMACOS SISTEMA ENDOCRINO Y DEL METABOLISMO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,4,'NUTRICION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,5,'SOLUCIONES PARENTERALES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,6,'FARMACOS HEMATOLOGICOS E INMUNOMODULADORES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,7,'FARMACOS QUE ACTUAN SOBRE EL SISTEMA INMUNE');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,8,'FARMACOS QUE ACTUAN SOBRE SISTEMA NERVIOSO CENTRAL');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,9,'FARMACOS ANESTESICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,10,'FARMACOS ANALGESICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,11,'FARMACOS OFTALMOLOGICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,12,'FARMACOS OTORRINOLARINGOLOGICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,13,'FARMACOS QUE ACTUAN SOBRE APARATO CARDIOVASCULAR');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,14,'FARMACOS DE VIAS RESPIRATORIAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,15,'FARMACOS DEL APARATO DIGESTIVO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,16,'FARMACOS QUE ACTUAN SOBRE EL APARATO URINARIO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,17,'FARMACOS GINECOLOGICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,18,'FARMACOS DERMATOLOGICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,19,'FARMACOS ANTIINFLAMATORIOS Y ANTIRREUMATICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,20,'FARMACOS ANTIALERGICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,21,'FARMACOS PARA TOXICOLOGIA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,22,'FARMACOS ONCOLOGICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,23,'OTROS FARMACOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,6,1,'ACTIVOS INTANGIBLES');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (5,6,2,'PROGRAMAS DE COMPUTACION Y SIMILARES', date '2010-03-12', 'Reestructura del Catálogo TIC');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,10,2,'SERVICIOS TIC OFRECIDOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,4,10,'DOCUMENTOS ELECTRONICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (2,4,11,'DOCUMENTOS ELECTRONICOS', date '2011-05-12', '');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (1,1,1,'SERVICIOS PERSONALES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,6,7,'TASAS, CONTRIBUCIONES, MULTAS Y OTROS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,3,10,'PASAJES AEREOS/ MARITIMOS/ TERRESTRES FUERA DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,9,9,'OTRAS MAQUINAS, EQUIPOS Y MOBILIARIOS NUEVOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,2,9,'OTRAS EDIFICACIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,4,9,'OTROS OBRAS URBANISTICAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,6,9,'OTRAS MEJORAS DE TIERRAS Y PLANTACIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,8,9,'OTRAS REPARACIONES MAYORES Y EXTRAORDINARIAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,3,9,'OTRAS MAQUINAS, EQUIPOS Y MOBILIARIO EXISTENTE');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (12,2,1,'ANCAP');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,20,'MANTENIMIENTO DE PLATAFORMAS DE DATA CENTER ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,33,'OTROS SERVICIOS CONTRATADOS ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,34,'SERVICIO DE VALOR AGREGADO ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,35,'SERVICIOS DE APLICACIONES DE TERCEROS ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,37,'SOFTWARE DE VIRTUALIZACION ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,43,'HARDWARE Y SOFTWARE ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,48,'OBRA CONMUTACION ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,51,'OBRA P/INSTALACION HARDWARE Y SOFTWARE ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,53,'OBRA PARA RED CELULAR ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,56,'OTROS SERVICIOS PROFESIONALES CONTRATADOS ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,61,'ANTEL', date '2024-08-27', 'Se modifica');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,6,10,'EQUIPOS DE SEÑALIZACION DE TRANSPORTE AEREO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,5,11,'MAQUINARIA FERROVIARIA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,2,9,'OTROS MAQUINAS Y EQUIPOS DE OFICINA Y SIMILARES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,4,9,'OTROS EQUIPOS EDUCACIONALES, CULTURALES Y RECREATIVOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,13,24,'OTROS');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,4,'MATERIAL PARA REDES', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,12,'ARRENDAMIENTO DE EQUIPOS Y SERVICIOS PARA RED INTERNACIONAL', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,16,'SERVICIO ADICIONAL ROAMING', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,17,'COMISIONES POR VENTAS', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,21,'MANTENIMIENTO INFRAESTRUCTURA FISICA DE DATA CENTER ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,23,'MANTENIMIENTO, SOPORTE Y REPARACION DE CENTRALES ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,25,'SERVICIOS DE DESMANTELAMIENTO ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,32,'GASTOS DE FIDELIZACION ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,44,'REPUESTOS MAQUINARIA EQUIPOS TELECOMUNICACIONES ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,45,'TERRENOS ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,47,'CONSULTORIA INVERSION ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,60,'ANTEL', date '2024-08-14', 'Se elimina para que quede con el numero 1');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (10,43,24,'DATOS Y BASES DE DATOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,4,12,'DOCUMENTOS DE IDENTIFICACION DE PERSONAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (11,1,1,'OTROS GASTOS');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,2,'CABLE FIBRA OPTICA', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,3,'EQUIPO LOCAL DEL CLIENTE', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,5,'MATERIALES ELECTRICOS', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,7,'TARJETA SIM', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,8,'TRAFICO INTERNACIONAL', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,10,'ARRENDAMIENTO DE SITIOS PARA RADIOBASES', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,13,'ARRENDAMIENTO DE TRANSITO IP PARA RED INTERNACIONAL', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,15,'OPERACION Y MANTENIMIENTO ENLACES INTERNACIONALES', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,18,'EQUIPOS INDUSTRIALES ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,19,'MANTENIMIENTO DE CENTRALES Y OTROS EQUIPOS', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,28,'CAPACITACION PERSONAL FUERA DEL PAIS ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,30,'CONTENIDOS ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,31,'GASTOS COMUNES ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,36,'SERVICIOS DE CONTACT CENTER ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,38,'ACCESORIO PARA TERMINAL MOVIL ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,39,'ACCESORIOS APARATOS TELEFONIA CELULAR ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,40,'ANTEL BOX ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,41,'TERMINAL MOVIL ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,42,'WIFIMAX ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,46,'OBRA CONSTRUCCION, EDIFICIOS Y CAMINOS ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,57,'SOFTWARE ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,58,'SUBSIDIO SERVICIOS COMUNITARIOS ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,59,'SUSCRIPCIONES ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,10,1,'SERVICIOS TIC CONTRATADOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,5,10,'AERONAVES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (12,3,1,'ANTEL');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,6,'OTROS MATERIALES DE FIBRA OPTICA', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,9,'TRANSPORTE ENCOMIENDAS Y CORRESPONDENCIA', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,24,'OTROS MANTENIMIENTOS Y REPARACIONES ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,26,'GASTOS ASOCIADOS A SUBSIDIARIAS ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,27,'MANTENIMIENTO Y REPARACION DE SOFTWARE ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,29,'OTROS SERVICIOS PROFESIONALES ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,49,'OBRA P/INST EQ. AUXILIARES ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,50,'OBRA P/INSTALACION EQUIPOS TELECOMUNICACIONES ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,52,'OBRA P/RED DE DATOS ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,54,'OBRA PLANTA EXTERNA ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (3,8,3,'CONTRATACION DE SERVICIOS TIC', date '2010-05-04', '');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (10,43,19,'DISPOSITIVOS DE COMUNICACIONES Y ACCESORIOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (10,43,20,'DISPOSITIVOS DE TECNOLOGIAS DE LA INFORMACION Y TELECOMUNICACIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (10,43,21,'EQUIPOS INFORMATICOS Y ACCESORIOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (10,43,22,'EQUIPOS DE REDES DE COMUNICACIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (10,43,23,'SOFTWARE DE BASE Y APLICACIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (12,1,1,'UTE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,11,'ARRENDAMIENTO DE CAPACIDADES PARA RED INTERNACIONAL', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,14,'ARRENDAMIENTO INMUEBLES', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,22,'MANTENIMIENTO Y REPARACION DE PLATAFORMAS ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (12,3,55,'OBRA TRANSMISION INTERNACIONAL ', date '2024-08-14', 'ES SUBCLASE');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,9,4,'SERVICIOS DE INSTALACION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,8,9,'OTROS MOBILIARIOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,1,1,'TERRENOS PARA EDIFICACION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,1,2,'TIERRAS PARA USO AGROPEC., FORESTAL Y OBRAS DE COMUNICACION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,1,3,'TERRENOS PARA SANEAMIENTO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,1,9,'OTRAS TIERRAS Y TERRENOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,8,9,'OTROS PRODUCTOS METALICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,1,9,'OTROS ALIMENTOS Y PROD.AGROPECUARIOS, FORESTALES Y MARITIMOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,6,9,'OTROS PROD.QUIM.Y CONEXOS EXCEPTO MEDIC.Y ANTISEP.USO HUMANO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,7,9,'OTROS PRODUCTOS MINERALES NO METALICOS Y DE MADERA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,9,9,'OTROS MATERIALES Y SUMINISTROS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,1,9,'OTROS SERVICIOS BASICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,5,9,'OTROS ARRENDAMIENTOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,3,3,'EQUIPOS DE OPTICA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,2,9,'OTROS EDIFICIOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,5,9,'OTROS ACTIVOS FINANCIEROS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,1,4,'DE GENERACION Y TRANSMISION ENERGETICA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,3,5,'PASAJES MARITIMOS FUERA DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,4,2,'SERVICIO DE MUDANZA FUERA DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,4,3,'ALMACENAJE DENTRO DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,4,4,'ALMACENAJE FUERA DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,4,6,'FLETES Y OTROS GASTOS DE TRANSPORTE AEREO EN EL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,4,7,'FLETES Y OTROS GASTOS DE TRANSPORTE TERRESTRE FUERA DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,4,8,'FLETES Y OTROS GASTOS DE TRANSPORTE AEREO FUERA DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,4,9,'FLETES Y OTROS GASTOS DE TRANSPORTE MARITIMO Y FLUVIAL');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,3,8,'OTRAS OBRAS SANITARIAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,6,3,'COMISIONES POR VENTA DE VALORES FISCALES,POSTALES Y SIMILAR');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,3,4,'OTROS ARTICULOS DE CUERO Y PIEL');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,5,9,'OTROS EQUIPOS DE TRANSPORTE');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (2,4,9,'OTROS PROD. DE PAPEL, LIBROS, DOC. IMPRESOS Y DIGITALES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,2,3,'FOTOGRAFIAS, FILMACIONES Y GRABACIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,5,9,'OTRAS INSTALACIONES DE TRASMISION Y DISTRIBUCION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,8,1,'DE INMUEBLES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,8,2,'DE INSTALACIONES DE TRANSMISION Y DISTRIBUCION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,8,3,'DE MAQUINAS Y EQUIPOS');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (2,5,7,'ENERGIA NUCLEAR', date '2012-06-18', '');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (2,5,9,'OTROS', date '2012-07-06', 'NO CORRESPONDE');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (4,6,9,'OTROS', date '2011-02-22', 'Se elimina porque esta vacia');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,6,2,'PRIMAS Y OTROS GASTOS DE SEGURO FUERA DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,4,1,'BOVINOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,4,2,'OVINOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,4,3,'EQUINOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,2,7,'EDIFICIOS PARA OTROS SERVICIOS PUBLICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,3,1,'DE PRODUCCION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,3,2,'DE OFICINA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,3,3,'MEDICOS-SANITARIOS Y ODONTOLOGICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,3,4,'EDUCACIONALES, CULTURALES Y RECREATIVOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,3,5,'DE TRANSPORTE');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,3,6,'DE COMUNICACIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,3,7,'MOTORES Y PARTES PARA REEMPLAZO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,3,8,'MOBILIARIO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (5,5,2,'VALORES PUBLICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,1,1,'CARRETERAS Y CAMINOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,1,2,'CALLES Y ACERAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,1,3,'PUENTES Y TUNELES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,2,1,'EDIFICIOS PARA OFICINAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,2,2,'VIVIENDAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,2,3,'EDIFICACIONES PARA USO PRODUCTIVO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,2,4,'EDIFICACIONES PARA ENSEÑANZA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,2,5,'EDIFICACIONES PARA SALUD');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,2,7,'EDIFICACIONES PARA OTROS SERVICIOS PUBLICOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,3,1,'OBRAS DE EMBALSE');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,3,2,'CAPTACION, EMBALSAMIENTO, Y DISTRIBUCION DE AGUAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,3,3,'OBRAS HIDRAULICAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,3,4,'OBRAS HIDROELECTRICAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,3,5,'OBRAS ELECTRICAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,3,6,'SANEAMIENTO DE TIERRAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,3,7,'ALCANTARILLADO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,4,1,'PARQUES Y PASEOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,4,2,'DISEÑO DE ESPACIOS LIBRES PARA  DEPORTE,  Y RECREACION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,4,3,'MONUMENTOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,5,1,'LINEAS DE TRASMISION Y REDES DE DISTRIBUCION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,5,2,'GASODUCTOS, OLEODUCTOS Y REDES DE DISTRIBUCION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,5,3,'LINEAS Y REDES TELEFONICAS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,5,4,'INSTALACION DE DEMARCACION Y SEÑALIZACION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,6,1,'DEFORESTACION DE TERRENOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,6,2,'PLANTACIONES Y OBRAS FORESTALES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,6,3,'PLANTACIONES INDUSTRIALES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,6,4,'RIEGO Y DEFENSA CONTRA INUNDACIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,7,1,'DE POZOS PETROLIFEROS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,7,2,'DE OTROS MINERALES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,9,0,'ACTIVOS NUEVOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,7,9,'OTROS SERVICIOS CONTRATADOS PARA MAN.Y REP. MENORES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,5,5,'ARRENDAMIENTO DE MAQUINAS Y EQUIPOS DE CONSTRUCCION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,5,6,'ARRENDAMIENTO DE EQUIPOS DE TRANSPORTE Y SIMILARES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,5,7,'EMBARCACIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,6,1,'PRIMAS Y OTROS GASTOS DE SEGUROS DENTRO DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,6,4,'COMISIONES BANCARIAS Y DE CAMBIO DENTRO DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,6,6,'OTRAS COMISIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,7,1,'MANTENIMIENTO Y REP.MENORES DE INMUEBLES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,7,2,'MANTENIMIENTO Y REP.MENORES DE INSTALACIONES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,7,3,'MANTENIMIENTO Y REP.MENORES DE MAQ.Y EQUIPOS INDUSTRIALES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,7,4,'MANTENIMIENTO Y REP.MENORES DE OTRAS MAQUINAS Y EQUIPOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,7,5,'MANTENIMIENTO Y REP.MENORES DE EQ. DE TRANSPORTE Y SIMILARES');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,8,9,'OTROS SERVICIOS PROFESIONALES CONTRATADOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,8,1,'SERV.PROFESIONALES CONTRATADOS PARA PROYECTO');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (6,1,7,'OBRAS DE DEMARCACION Y SEÑALIZACION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,9,9,'OTROS SERVICIOS CONTRATADOS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,9,1,'SERVICIOS DE LIMPIEZA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,9,2,'SERVICIOS DE VIGILANCIA');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (3,9,3,'SERVICIOS DE COMPUTACION', date '2010-07-14', 'Ver Rama 3-10 (TICS)');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,2,2,'IMPRESIONES, REPRODUCCIONES Y ENCUADERNACION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,1,1,'MAQUINARIA Y EQUIPOS DE PRODUCCION INDUSTRIAL');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,1,2,'MAQUINARIA Y EQUIPOS DE PRODUCCION AGRICOLA');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,1,3,'MAQUINARIA Y EQUIPOS DE CONSTRUCCION');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,3,1,'PASAJES TERRESTRES DENTRO DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,3,2,'PASAJES AEREOS DENTRO DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,3,3,'PASAJES TERRESTRES FUERA DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,3,4,'PASAJES AEREOS FUERA DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,3,6,'VIATICOS DENTRO DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,3,7,'VIATICOS FUERA DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,3,8,'OTROS GASTOS DE TRASLADO DENTRO DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (3,3,9,'OTROS GASTOS DE TRASLADO FUERA DEL PAIS');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,2,1,'MAQUINAS DE ESCRIBIR');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,2,2,'MAQUINAS DE CALCULAR, REGISTRADORAS Y SIMILARES');
insert into clases(fami_cod, subf_cod, cod, descripcion, fecha_baja, motivo_baja) values (4,2,3,'EQUIPOS DE PROCESAMIENTO DE DATOS', date '2010-03-12', 'Reestructura del Catálogo TIC');
insert into clases(fami_cod, subf_cod, cod, descripcion) values (4,2,4,'EQUIPOS DE IMPRENTA Y SIMILARES');
